<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>3</Battery>
			<DateTime>2016-01-26T10:45:28</DateTime>
			<Duration>69</Duration>
			<Depth>
				<Max>15.27</Max>
				<Avg>11.01</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>300</SurfaceTime>
				<NumberInSeries>6</NumberInSeries>
				<SurfacePressure>100500</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.28</Depth>
				<Temperature>302.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.28</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>2.15</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>2.98</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>3.74</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>4.49</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>5.16</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>5.88</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>6.61</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>7.34</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>8.130000000000001</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>8.99</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>9.83</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>10.71</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>11.61</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>12.48</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>13.34</Depth>
				<Temperature>301.15</Temperature>
				<Events>
					<Notify>
						<Type>Depth</Type>
					</Notify>
				</Events>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>14.11</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>14.67</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>15.14</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>15.27</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>15.24</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>15.22</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>15.21</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>15.12</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>14.93</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>14.82</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>14.71</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>14.63</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>14.57</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>14.54</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>14.53</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>14.49</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>14.54</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>14.58</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>14.49</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>14.46</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>14.47</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>14.41</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>39</Time>
				<Depth>14.34</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>14.26</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>41</Time>
				<Depth>14.21</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>42</Time>
				<Depth>14.17</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>43</Time>
				<Depth>14.15</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>44</Time>
				<Depth>14.11</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>45</Time>
				<Depth>14.09</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>46</Time>
				<Depth>14.08</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>47</Time>
				<Depth>14.11</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>48</Time>
				<Depth>14.16</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>49</Time>
				<Depth>14.25</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>50</Time>
				<Depth>14.31</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>51</Time>
				<Depth>14.14</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>52</Time>
				<Depth>13.85</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>53</Time>
				<Depth>13.43</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>54</Time>
				<Depth>12.88</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>55</Time>
				<Depth>12.22</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>56</Time>
				<Depth>11.51</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>57</Time>
				<Depth>10.74</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>58</Time>
				<Depth>9.94</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>59</Time>
				<Depth>9.15</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>60</Time>
				<Depth>8.369999999999999</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>61</Time>
				<Depth>7.56</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>62</Time>
				<Depth>6.71</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>63</Time>
				<Depth>5.76</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>64</Time>
				<Depth>4.77</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>65</Time>
				<Depth>3.8</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>66</Time>
				<Depth>2.8</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>67</Time>
				<Depth>1.82</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>68</Time>
				<Depth>0.9300000000000001</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>69</Time>
				<Depth>0.49</Depth>
				<Temperature>301.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
