<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>3</Battery>
			<DateTime>2016-05-24T11:10:13</DateTime>
			<Duration>86</Duration>
			<Depth>
				<Max>18.52</Max>
				<Avg>11.05</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>0</SurfaceTime>
				<NumberInSeries>1</NumberInSeries>
				<SurfacePressure>101000</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.24</Depth>
				<Temperature>303.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.24</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>1.95</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>2.4</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>3.03</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>3.57</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>4.19</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>4.83</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>5.45</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>5.78</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>6.24</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>6.75</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>7.26</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>7.84</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>8.470000000000001</Depth>
				<Temperature>303.15</Temperature>
				<Events>
					<Notify>
						<Type>Depth</Type>
					</Notify>
				</Events>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>9.09</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>9.68</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>10.2</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>10.76</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>11.31</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>11.81</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>12.36</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>12.92</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>13.48</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>14.03</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>14.63</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>15.19</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>15.78</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>16.49</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>16.99</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>17.54</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>17.92</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>18.16</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>18.34</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>18.43</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>18.46</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>18.47</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>18.49</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>18.5</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>39</Time>
				<Depth>18.52</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>18.52</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>41</Time>
				<Depth>18.5</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>42</Time>
				<Depth>18.34</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>43</Time>
				<Depth>18.03</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>44</Time>
				<Depth>17.74</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>45</Time>
				<Depth>17.61</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>46</Time>
				<Depth>17.55</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>47</Time>
				<Depth>17.47</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>48</Time>
				<Depth>17.32</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>49</Time>
				<Depth>17.15</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>50</Time>
				<Depth>16.78</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>51</Time>
				<Depth>16.2</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>52</Time>
				<Depth>15.78</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>53</Time>
				<Depth>15.59</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>54</Time>
				<Depth>15.4</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>55</Time>
				<Depth>15.13</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>56</Time>
				<Depth>14.6</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>57</Time>
				<Depth>13.89</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>58</Time>
				<Depth>13.32</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>59</Time>
				<Depth>13.06</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>60</Time>
				<Depth>12.88</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>61</Time>
				<Depth>12.61</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>62</Time>
				<Depth>12.12</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>63</Time>
				<Depth>11.44</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>64</Time>
				<Depth>10.8</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>65</Time>
				<Depth>10.5</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>66</Time>
				<Depth>10.22</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>67</Time>
				<Depth>9.75</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>68</Time>
				<Depth>9.09</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>69</Time>
				<Depth>8.310000000000001</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>70</Time>
				<Depth>7.87</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>71</Time>
				<Depth>7.58</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>72</Time>
				<Depth>7.21</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>73</Time>
				<Depth>6.7</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>74</Time>
				<Depth>6.03</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>75</Time>
				<Depth>5.32</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>76</Time>
				<Depth>4.8</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>77</Time>
				<Depth>4.52</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>78</Time>
				<Depth>4.15</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>79</Time>
				<Depth>3.69</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>80</Time>
				<Depth>3.14</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>81</Time>
				<Depth>2.55</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>82</Time>
				<Depth>1.97</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>83</Time>
				<Depth>1.42</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>84</Time>
				<Depth>0.98</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>85</Time>
				<Depth>0.57</Depth>
				<Temperature>301.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>86</Time>
				<Depth>0.3</Depth>
				<Temperature>301.15</Temperature>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
