<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-05-12T13:02:34</DateTime>
			<Duration>76</Duration>
			<Depth>
				<Max>10.73</Max>
				<Avg>6.4</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>60</SurfaceTime>
				<NumberInSeries>17</NumberInSeries>
				<SurfacePressure>101300</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.55</Depth>
				<Temperature>297.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.55</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>2.44</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>3.05</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>3.83</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>4.39</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>4.91</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>5.63</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>6.17</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>6.72</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>7.44</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>7.9</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>8.4</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>9.119999999999999</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>9.529999999999999</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>9.810000000000001</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>10.13</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>10.36</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>10.54</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>10.66</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>10.57</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>10.48</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>10.45</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>10.54</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>10.61</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>10.73</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>10.7</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>10.62</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>10.54</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>10.53</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>10.55</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>10.57</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>10.55</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>10.52</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>10.3</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>10.08</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>9.83</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>9.48</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>9.44</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>39</Time>
				<Depth>9.5</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>9.33</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>41</Time>
				<Depth>9.26</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>42</Time>
				<Depth>9.220000000000001</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>43</Time>
				<Depth>9.15</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>44</Time>
				<Depth>9.039999999999999</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>45</Time>
				<Depth>8.99</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>46</Time>
				<Depth>8.9</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>47</Time>
				<Depth>8.869999999999999</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>48</Time>
				<Depth>8.83</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>49</Time>
				<Depth>8.140000000000001</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>50</Time>
				<Depth>7.62</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>51</Time>
				<Depth>7.18</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>52</Time>
				<Depth>6.46</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>53</Time>
				<Depth>5.93</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>54</Time>
				<Depth>5.33</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>55</Time>
				<Depth>4.41</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>56</Time>
				<Depth>3.66</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>57</Time>
				<Depth>3.13</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>58</Time>
				<Depth>2.51</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>59</Time>
				<Depth>1.67</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>60</Time>
				<Depth>1.04</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>61</Time>
				<Depth>0.6</Depth>
				<Temperature>297.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>62</Time>
				<Depth>0.52</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>63</Time>
				<Depth>0.51</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>64</Time>
				<Depth>0.51</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>65</Time>
				<Depth>0.58</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>66</Time>
				<Depth>0.63</Depth>
				<Temperature>297.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>67</Time>
				<Depth>0.67</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>68</Time>
				<Depth>0.64</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>69</Time>
				<Depth>0.5600000000000001</Depth>
				<Temperature>297.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>70</Time>
				<Depth>0.57</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>71</Time>
				<Depth>0.54</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>72</Time>
				<Depth>0.59</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>73</Time>
				<Depth>0.62</Depth>
				<Temperature>297.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>74</Time>
				<Depth>0.6</Depth>
				<Temperature>297.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>75</Time>
				<Depth>0.51</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>76</Time>
				<Depth>0.49</Depth>
				<Temperature>297.15</Temperature>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
