<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-08-20T14:47:36</DateTime>
			<Duration>36</Duration>
			<Depth>
				<Max>15.78</Max>
				<Avg>8.619999999999999</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>120</SurfaceTime>
				<NumberInSeries>12</NumberInSeries>
				<SurfacePressure>101000</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.65</Depth>
				<Temperature>293.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.65</Depth>
				<Temperature>293.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>3.53</Depth>
				<Temperature>293.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>4.48</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>5.75</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>6.82</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>7.86</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>9.33</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>10.4</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>11.38</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>12.69</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>13.49</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>14.32</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>15.22</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>15.56</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>15.78</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>15.72</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>15.24</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>14.55</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>13.58</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>12.83</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>12.06</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>10.98</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>10.16</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>9.33</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>8.27</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>7.47</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>6.68</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>5.62</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>4.95</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>4.42</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>3.55</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>2.77</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>2.15</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>1.35</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>0.6</Depth>
				<Temperature>288.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>0.12</Depth>
				<Temperature>288.15</Temperature>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
