<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-05-25T15:34:42</DateTime>
			<Duration>562</Duration>
			<Depth>
				<Max>10.36</Max>
				<Avg>4.73</Avg>
			</Depth>
			<Diving>
				<DiveMode>Air</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>6840</SurfaceTime>
				<NumberInSeries>2</NumberInSeries>
				<SurfacePressure>100900</SurfacePressure>
				<Algorithm>Suunto Technical RGBM</Algorithm>
				<Gases>
					<Gas>
						<State>Air</State>
						<Oxygen>0.210</Oxygen>
					</Gas>
				</Gases>
				<StartTissue>
					<CNS>0.0005468750000000001</CNS>
					<OTU>0.10546875</OTU>
					<Nitrogen>
						<Pressure>79000</Pressure>
						<Pressure>79000</Pressure>
						<Pressure>79300</Pressure>
						<Pressure>81100</Pressure>
						<Pressure>83900</Pressure>
						<Pressure>84700</Pressure>
						<Pressure>84700</Pressure>
						<Pressure>83200</Pressure>
						<Pressure>81600</Pressure>
					</Nitrogen>
					<RgbmNitrogen>0.9996185244525826</RgbmNitrogen>
				</StartTissue>
				<EndTissue>
					<CNS>0.0005468750000000001</CNS>
					<OTU>0.10546875</OTU>
					<OLF>0.0005468750000000001</OLF>
					<Nitrogen>
						<Pressure>110000</Pressure>
						<Pressure>104100</Pressure>
						<Pressure>96100</Pressure>
						<Pressure>90600</Pressure>
						<Pressure>88600</Pressure>
						<Pressure>87200</Pressure>
						<Pressure>86300</Pressure>
						<Pressure>84100</Pressure>
						<Pressure>82000</Pressure>
					</Nitrogen>
					<RgbmNitrogen>0.9973144121461814</RgbmNitrogen>
				</EndTissue>
			</Diving>
			<SampleInterval>20</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.51</Depth>
				<Temperature>299.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>3.66</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>3.29</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>60</Time>
				<Depth>4.6</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>80</Time>
				<Depth>5.4</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>100</Time>
				<Depth>7.17</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>120</Time>
				<Depth>8.529999999999999</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>140</Time>
				<Depth>9.43</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>160</Time>
				<Depth>10.21</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>180</Time>
				<Depth>10.02</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>200</Time>
				<Depth>8.359999999999999</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>220</Time>
				<Depth>5.9</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>240</Time>
				<Depth>3.37</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>256</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>256</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>259</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>259</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>260</Time>
				<Depth>0.43</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>280</Time>
				<Depth>0.16</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>300</Time>
				<Depth>0.53</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>320</Time>
				<Depth>0.39</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>339</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>339</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>340</Time>
				<Depth>0.62</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>341</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>341</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>344</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>344</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>346</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>346</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>360</Time>
				<Depth>4.51</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>380</Time>
				<Depth>5.06</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>400</Time>
				<Depth>4.71</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>420</Time>
				<Depth>4.73</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>440</Time>
				<Depth>4.15</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>460</Time>
				<Depth>2.78</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>480</Time>
				<Depth>2.34</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>500</Time>
				<Depth>2.25</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>520</Time>
				<Depth>3.38</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>540</Time>
				<Depth>4.56</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>560</Time>
				<Depth>4.31</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>580</Time>
				<Depth>3.24</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>600</Time>
				<Depth>2.4</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>620</Time>
				<Depth>1.39</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>625</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>625</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>626</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>626</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>640</Time>
				<Depth>1.27</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>650</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>650</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>660</Time>
				<Depth>1.13</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>677</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>677</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>680</Time>
				<Depth>0.5600000000000001</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>700</Time>
				<Depth>0.51</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>717</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>717</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>720</Time>
				<Depth>0.92</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>740</Time>
				<Depth>0.87</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>747</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>747</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>750</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>750</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
