<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-08-21T10:41:51</DateTime>
			<Duration>74</Duration>
			<Depth>
				<Max>24.95</Max>
				<Avg>14.65</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>540</SurfaceTime>
				<NumberInSeries>12</NumberInSeries>
				<SurfacePressure>101500</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.61</Depth>
				<Temperature>291.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.61</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>2.69</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>3.47</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>4.02</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>4.6</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>5.21</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>6.11</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>6.84</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>7.6</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>8.57</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>9.33</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>10.1</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>11.18</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>12.01</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>12.83</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>13.97</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>14.91</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>15.83</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>16.96</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>17.83</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>18.62</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>19.58</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>20.17</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>20.66</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>21.53</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>22.43</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>23.25</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>24.07</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>24.43</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>24.76</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>24.95</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>24.87</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>24.77</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>24.81</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>24.76</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>24.59</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>24.47</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>24.52</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>39</Time>
				<Depth>24.54</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>24.6</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>41</Time>
				<Depth>24.46</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>42</Time>
				<Depth>24.08</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>43</Time>
				<Depth>23.4</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>44</Time>
				<Depth>22.91</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>45</Time>
				<Depth>22.33</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>46</Time>
				<Depth>21.52</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>47</Time>
				<Depth>20.84</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>48</Time>
				<Depth>20.12</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>49</Time>
				<Depth>19.21</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>50</Time>
				<Depth>18.51</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>51</Time>
				<Depth>17.73</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>52</Time>
				<Depth>16.81</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>53</Time>
				<Depth>16.13</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>54</Time>
				<Depth>15.43</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>55</Time>
				<Depth>14.54</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>56</Time>
				<Depth>13.9</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>57</Time>
				<Depth>13.22</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>58</Time>
				<Depth>12.32</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>59</Time>
				<Depth>11.69</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>60</Time>
				<Depth>11.07</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>61</Time>
				<Depth>10.2</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>62</Time>
				<Depth>9.5</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>63</Time>
				<Depth>8.859999999999999</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>64</Time>
				<Depth>7.98</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>65</Time>
				<Depth>7.24</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>66</Time>
				<Depth>6.47</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>67</Time>
				<Depth>5.55</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>68</Time>
				<Depth>4.79</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>69</Time>
				<Depth>3.97</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>70</Time>
				<Depth>3</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>71</Time>
				<Depth>2.29</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>72</Time>
				<Depth>1.57</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>73</Time>
				<Depth>0.65</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>74</Time>
				<Depth>0.28</Depth>
				<Temperature>287.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
