<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-08-07T13:26:15</DateTime>
			<Duration>69</Duration>
			<Depth>
				<Max>7.57</Max>
				<Avg>5.79</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>60</SurfaceTime>
				<NumberInSeries>14</NumberInSeries>
				<SurfacePressure>100600</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.31</Depth>
				<Temperature>293.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.31</Depth>
				<Temperature>293.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>2.13</Depth>
				<Temperature>293.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>2.85</Depth>
				<Temperature>293.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>3.54</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>4.17</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>4.82</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>5.45</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>5.9</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>6.31</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>6.62</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>6.86</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>7.06</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>7.13</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>7.14</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>7.25</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>7.33</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>7.37</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>7.36</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>7.38</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>7.35</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>7.3</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>7.3</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>7.38</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>7.41</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>7.37</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>7.37</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>7.37</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>7.35</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>7.34</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>7.38</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>7.4</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>7.42</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>7.43</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>7.44</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>7.44</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>7.42</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>7.39</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>7.38</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>39</Time>
				<Depth>7.37</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>7.41</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>41</Time>
				<Depth>7.48</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>42</Time>
				<Depth>7.53</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>43</Time>
				<Depth>7.54</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>44</Time>
				<Depth>7.56</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>45</Time>
				<Depth>7.57</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>46</Time>
				<Depth>7.55</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>47</Time>
				<Depth>7.54</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>48</Time>
				<Depth>7.54</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>49</Time>
				<Depth>7.54</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>50</Time>
				<Depth>7.49</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>51</Time>
				<Depth>7.28</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>52</Time>
				<Depth>6.95</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>53</Time>
				<Depth>6.65</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>54</Time>
				<Depth>6.25</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>55</Time>
				<Depth>5.81</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>56</Time>
				<Depth>5.42</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>57</Time>
				<Depth>4.95</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>58</Time>
				<Depth>4.24</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>59</Time>
				<Depth>3.49</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>60</Time>
				<Depth>2.75</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>61</Time>
				<Depth>2.04</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>62</Time>
				<Depth>1.34</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>63</Time>
				<Depth>0.94</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>64</Time>
				<Depth>0.8100000000000001</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>65</Time>
				<Depth>0.69</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>66</Time>
				<Depth>0.59</Depth>
				<Temperature>288.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>67</Time>
				<Depth>0.55</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>68</Time>
				<Depth>0.52</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>69</Time>
				<Depth>0.46</Depth>
				<Temperature>289.15</Temperature>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
