<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-09-13T18:44:54</DateTime>
			<Duration>1063</Duration>
			<Depth>
				<Max>5.48</Max>
				<Avg>3.93</Avg>
			</Depth>
			<Diving>
				<DiveMode>Air</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>293640</SurfaceTime>
				<NumberInSeries>1</NumberInSeries>
				<SurfacePressure>101200</SurfacePressure>
				<Algorithm>Suunto Technical RGBM</Algorithm>
				<Gases>
					<Gas>
						<State>Air</State>
						<Oxygen>0.210</Oxygen>
					</Gas>
				</Gases>
				<StartTissue>
					<CNS>0</CNS>
					<OTU>0</OTU>
					<Nitrogen>
						<Pressure>79000</Pressure>
						<Pressure>79000</Pressure>
						<Pressure>79000</Pressure>
						<Pressure>79000</Pressure>
						<Pressure>79000</Pressure>
						<Pressure>79000</Pressure>
						<Pressure>79000</Pressure>
						<Pressure>79000</Pressure>
						<Pressure>79000</Pressure>
					</Nitrogen>
					<RgbmNitrogen>1</RgbmNitrogen>
				</StartTissue>
				<EndTissue>
					<CNS>0</CNS>
					<OTU>0</OTU>
					<OLF>0</OLF>
					<Nitrogen>
						<Pressure>111000</Pressure>
						<Pressure>108000</Pressure>
						<Pressure>101200</Pressure>
						<Pressure>93300</Pressure>
						<Pressure>87200</Pressure>
						<Pressure>83400</Pressure>
						<Pressure>82000</Pressure>
						<Pressure>80500</Pressure>
						<Pressure>79800</Pressure>
					</Nitrogen>
					<RgbmNitrogen>1</RgbmNitrogen>
				</EndTissue>
			</Diving>
			<SampleInterval>20</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.24</Depth>
				<Temperature>291.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>1.91</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>2.04</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>60</Time>
				<Depth>2.47</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>80</Time>
				<Depth>2.98</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>100</Time>
				<Depth>3.07</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>120</Time>
				<Depth>3.03</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>140</Time>
				<Depth>3.32</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>160</Time>
				<Depth>3.48</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>180</Time>
				<Depth>3.63</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>200</Time>
				<Depth>3.96</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>220</Time>
				<Depth>3.89</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>240</Time>
				<Depth>3.79</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>260</Time>
				<Depth>3.85</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>280</Time>
				<Depth>3.97</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>300</Time>
				<Depth>4.11</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>320</Time>
				<Depth>4.21</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>340</Time>
				<Depth>4.34</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>360</Time>
				<Depth>4.46</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>380</Time>
				<Depth>4.38</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>400</Time>
				<Depth>4.76</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>420</Time>
				<Depth>4.93</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>440</Time>
				<Depth>4.9</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>460</Time>
				<Depth>5.01</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>480</Time>
				<Depth>5.13</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>500</Time>
				<Depth>5.02</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>520</Time>
				<Depth>5.48</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>540</Time>
				<Depth>5.13</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>560</Time>
				<Depth>5.26</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>580</Time>
				<Depth>5.16</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>600</Time>
				<Depth>4.97</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>620</Time>
				<Depth>3.86</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>640</Time>
				<Depth>2.16</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>646</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>646</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>649</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>649</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>660</Time>
				<Depth>0.39</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>675</Time>
				<Events>
					<State>
						<Type>Wet Outside</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>675</Time>
				<Events>
					<State>
						<Type>Wet Outside</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>680</Time>
				<Depth>0.22</Depth>
				<Temperature>291.15</Temperature>
				<Events>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>700</Time>
				<Depth>0.3</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>720</Time>
				<Depth>0.34</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>738</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>738</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>740</Time>
				<Depth>1.37</Depth>
				<Temperature>291.15</Temperature>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>760</Time>
				<Depth>3.92</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>780</Time>
				<Depth>4.73</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>800</Time>
				<Depth>4.6</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>820</Time>
				<Depth>4.32</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>840</Time>
				<Depth>4.08</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>860</Time>
				<Depth>3.97</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>880</Time>
				<Depth>3.98</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>900</Time>
				<Depth>3.74</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>920</Time>
				<Depth>3.47</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>940</Time>
				<Depth>2.88</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>960</Time>
				<Depth>2.82</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>980</Time>
				<Depth>3.29</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>1000</Time>
				<Depth>3.64</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>1020</Time>
				<Depth>3.59</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>1040</Time>
				<Depth>4.12</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>1060</Time>
				<Depth>4.46</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>1080</Time>
				<Depth>4.12</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>1100</Time>
				<Depth>4.17</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>1120</Time>
				<Depth>4.14</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>1140</Time>
				<Depth>4.14</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>1157</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1157</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
