<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-06-11T10:01:27</DateTime>
			<Duration>33</Duration>
			<Depth>
				<Max>5.16</Max>
				<Avg>4.42</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>0</SurfaceTime>
				<NumberInSeries>4</NumberInSeries>
				<SurfacePressure>101300</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.95</Depth>
				<Temperature>287.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.95</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>3.33</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>3.97</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>4.54</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>4.82</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>4.88</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>4.86</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>4.88</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>4.83</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>4.75</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>5.01</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>5.14</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>5.12</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>5.15</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>5.13</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>5.14</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>5.15</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>5.16</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>5.13</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>5.16</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>5.11</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>5.15</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>5.09</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>5.04</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>5.01</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>4.99</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>5</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>4.84</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>4.24</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>3.5</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>2.21</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>1.27</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>0.49</Depth>
				<Temperature>286.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
