<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-09-13T19:12:29</DateTime>
			<Duration>3515</Duration>
			<Depth>
				<Max>14.6</Max>
				<Avg>7.2</Avg>
			</Depth>
			<Diving>
				<DiveMode>Air</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>480</SurfaceTime>
				<NumberInSeries>2</NumberInSeries>
				<SurfacePressure>101200</SurfacePressure>
				<Algorithm>Suunto Technical RGBM</Algorithm>
				<Gases>
					<Gas>
						<State>Air</State>
						<Oxygen>0.210</Oxygen>
					</Gas>
				</Gases>
				<StartTissue>
					<CNS>0</CNS>
					<OTU>0</OTU>
					<Nitrogen>
						<Pressure>100100</Pressure>
						<Pressure>102000</Pressure>
						<Pressure>98500</Pressure>
						<Pressure>92300</Pressure>
						<Pressure>86900</Pressure>
						<Pressure>83300</Pressure>
						<Pressure>82000</Pressure>
						<Pressure>80500</Pressure>
						<Pressure>79800</Pressure>
					</Nitrogen>
					<RgbmNitrogen>0.9109788662546731</RgbmNitrogen>
				</StartTissue>
				<EndTissue>
					<CNS>0.0065625</CNS>
					<OTU>1.265625</OTU>
					<OLF>0.0065625</OLF>
					<Nitrogen>
						<Pressure>101000</Pressure>
						<Pressure>108500</Pressure>
						<Pressure>118900</Pressure>
						<Pressure>121600</Pressure>
						<Pressure>114000</Pressure>
						<Pressure>102600</Pressure>
						<Pressure>96700</Pressure>
						<Pressure>88900</Pressure>
						<Pressure>84300</Pressure>
					</Nitrogen>
					<RgbmNitrogen>0.8840619516289006</RgbmNitrogen>
				</EndTissue>
			</Diving>
			<SampleInterval>20</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.62</Depth>
				<Temperature>291.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>4.8</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>5.66</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>60</Time>
				<Depth>6.26</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>80</Time>
				<Depth>6.45</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>100</Time>
				<Depth>6.53</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>120</Time>
				<Depth>6.61</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>140</Time>
				<Depth>6.72</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>160</Time>
				<Depth>7.26</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>180</Time>
				<Depth>8.08</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>200</Time>
				<Depth>8.970000000000001</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>220</Time>
				<Depth>9.619999999999999</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>240</Time>
				<Depth>10.07</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>260</Time>
				<Depth>10.02</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>280</Time>
				<Depth>10.2</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>300</Time>
				<Depth>10.32</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>320</Time>
				<Depth>10.41</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>340</Time>
				<Depth>10.5</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>360</Time>
				<Depth>10.48</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>380</Time>
				<Depth>10.64</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>400</Time>
				<Depth>10.99</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>420</Time>
				<Depth>11.16</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>440</Time>
				<Depth>11.96</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>460</Time>
				<Depth>12.11</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>480</Time>
				<Depth>12.25</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>500</Time>
				<Depth>12.14</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>520</Time>
				<Depth>12.19</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>540</Time>
				<Depth>12.31</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>560</Time>
				<Depth>12.24</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>580</Time>
				<Depth>12.11</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>600</Time>
				<Depth>11.55</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>620</Time>
				<Depth>12.01</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>640</Time>
				<Depth>11.87</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>660</Time>
				<Depth>11.96</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>680</Time>
				<Depth>12</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>700</Time>
				<Depth>11.92</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>720</Time>
				<Depth>12</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>740</Time>
				<Depth>12.2</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>760</Time>
				<Depth>12.06</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>780</Time>
				<Depth>12.08</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>800</Time>
				<Depth>12.15</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>820</Time>
				<Depth>11.89</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>840</Time>
				<Depth>12.02</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>860</Time>
				<Depth>11.71</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>880</Time>
				<Depth>11.93</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>900</Time>
				<Depth>11.95</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>920</Time>
				<Depth>12.19</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>940</Time>
				<Depth>11.53</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>960</Time>
				<Depth>11.52</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>980</Time>
				<Depth>11.8</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>1000</Time>
				<Depth>11.95</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>1020</Time>
				<Depth>12.11</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>1040</Time>
				<Depth>11.7</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>1060</Time>
				<Depth>11.45</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>1080</Time>
				<Depth>11.93</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>1100</Time>
				<Depth>12.25</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>1120</Time>
				<Depth>12.26</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>1140</Time>
				<Depth>12.51</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>1160</Time>
				<Depth>12.34</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>1180</Time>
				<Depth>12.76</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>1200</Time>
				<Depth>13.3</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>1220</Time>
				<Depth>13.83</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>1240</Time>
				<Depth>14.16</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>1260</Time>
				<Depth>14.51</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>1280</Time>
				<Depth>14.19</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>1300</Time>
				<Depth>14.01</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>1320</Time>
				<Depth>13.96</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>1340</Time>
				<Depth>14.46</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>1360</Time>
				<Depth>13.95</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>1380</Time>
				<Depth>14</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>1400</Time>
				<Depth>14.16</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>1420</Time>
				<Depth>14.37</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>1440</Time>
				<Depth>14.03</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>1460</Time>
				<Depth>14.25</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>1480</Time>
				<Depth>14.03</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>1500</Time>
				<Depth>13.17</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>1520</Time>
				<Depth>12.52</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>1540</Time>
				<Depth>11.79</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>1560</Time>
				<Depth>10.58</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>1580</Time>
				<Depth>10.66</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>1600</Time>
				<Depth>10.05</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>1620</Time>
				<Depth>9.310000000000001</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>1640</Time>
				<Depth>8.66</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>1660</Time>
				<Depth>8.59</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>1680</Time>
				<Depth>8.15</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>1700</Time>
				<Depth>8.5</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>1720</Time>
				<Depth>7.95</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>1740</Time>
				<Depth>8.060000000000001</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>1760</Time>
				<Depth>7.56</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>1780</Time>
				<Depth>6.72</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>1800</Time>
				<Depth>6.59</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>1820</Time>
				<Depth>6.37</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>1840</Time>
				<Depth>6.48</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>1860</Time>
				<Depth>6.23</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>1880</Time>
				<Depth>5.93</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>1900</Time>
				<Depth>5.92</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>1920</Time>
				<Depth>5.45</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>1940</Time>
				<Depth>5.09</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>1960</Time>
				<Depth>4.9</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>1980</Time>
				<Depth>5.01</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2000</Time>
				<Depth>4.24</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2020</Time>
				<Depth>4.03</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2040</Time>
				<Depth>4.28</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2060</Time>
				<Depth>3.92</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2080</Time>
				<Depth>4.23</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2100</Time>
				<Depth>4.67</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2120</Time>
				<Depth>4.31</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2140</Time>
				<Depth>4.42</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2160</Time>
				<Depth>4.32</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2180</Time>
				<Depth>3.81</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2200</Time>
				<Depth>3.6</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2220</Time>
				<Depth>3.3</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2240</Time>
				<Depth>2.63</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2260</Time>
				<Depth>3.02</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2280</Time>
				<Depth>2.95</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2300</Time>
				<Depth>2.96</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2320</Time>
				<Depth>2.88</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2340</Time>
				<Depth>2.82</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2360</Time>
				<Depth>2.8</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2380</Time>
				<Depth>3.13</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2400</Time>
				<Depth>2.82</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2420</Time>
				<Depth>2.72</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2440</Time>
				<Depth>2.26</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2460</Time>
				<Depth>2.34</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2480</Time>
				<Depth>2.54</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2500</Time>
				<Depth>2</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2520</Time>
				<Depth>2.05</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2540</Time>
				<Depth>2.56</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2560</Time>
				<Depth>1.94</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2580</Time>
				<Depth>1.53</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2583</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>2583</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>2586</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>2586</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>2599</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>2599</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>2600</Time>
				<Depth>0.95</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2602</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>2602</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>2620</Time>
				<Depth>1.26</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2625</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>2625</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>2626</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>2626</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>2627</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>2627</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>2637</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>2637</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>2640</Time>
				<Depth>0.47</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2660</Time>
				<Depth>0.44</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2680</Time>
				<Depth>0.4</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2682</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>2682</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>2683</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>2683</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>2684</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>2684</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>2698</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>2698</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>2700</Time>
				<Depth>1.3</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2720</Time>
				<Depth>1.74</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2740</Time>
				<Depth>2.65</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2760</Time>
				<Depth>2.95</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2780</Time>
				<Depth>2.7</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2800</Time>
				<Depth>2.72</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2820</Time>
				<Depth>2.8</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2840</Time>
				<Depth>2.88</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2860</Time>
				<Depth>3.27</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2880</Time>
				<Depth>3.3</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2900</Time>
				<Depth>2.92</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2920</Time>
				<Depth>2.77</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2940</Time>
				<Depth>2.86</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2960</Time>
				<Depth>3.15</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2980</Time>
				<Depth>2.83</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>3000</Time>
				<Depth>2.52</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>3020</Time>
				<Depth>2.66</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>3040</Time>
				<Depth>2.74</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>3060</Time>
				<Depth>3.19</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>3080</Time>
				<Depth>3.25</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>3100</Time>
				<Depth>3.24</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>3120</Time>
				<Depth>2.74</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>3140</Time>
				<Depth>2.75</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>3160</Time>
				<Depth>2.39</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>3180</Time>
				<Depth>2.26</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>3195</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>3195</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>3199</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>3199</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>3200</Time>
				<Depth>0.49</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>3212</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>3212</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>3215</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>3215</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>3216</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>3216</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>3220</Time>
				<Depth>0.94</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>3224</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>3224</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>3240</Time>
				<Depth>2.09</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>3260</Time>
				<Depth>2.68</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>3280</Time>
				<Depth>2.49</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>3300</Time>
				<Depth>2.59</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>3320</Time>
				<Depth>2.87</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>3340</Time>
				<Depth>2.85</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>3360</Time>
				<Depth>3.24</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>3380</Time>
				<Depth>3.17</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>3400</Time>
				<Depth>3.08</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>3420</Time>
				<Depth>3.04</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>3440</Time>
				<Depth>2.81</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>3460</Time>
				<Depth>2.79</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>3480</Time>
				<Depth>2.66</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>3496</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>3496</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>3499</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>3499</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>3500</Time>
				<Depth>0.42</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>3504</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>3504</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>3505</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>3505</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>3506</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>3506</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>3512</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>3512</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>3520</Time>
				<Depth>2.03</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>3540</Time>
				<Depth>2.32</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>3560</Time>
				<Depth>2.41</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>3580</Time>
				<Depth>2.2</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>3600</Time>
				<Depth>2.13</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>3620</Time>
				<Depth>2.21</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>3640</Time>
				<Depth>2.23</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>3651</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>3651</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
