<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-06-18T16:03:57</DateTime>
			<Duration>55</Duration>
			<Depth>
				<Max>20.53</Max>
				<Avg>11.06</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>240</SurfaceTime>
				<NumberInSeries>17</NumberInSeries>
				<SurfacePressure>102200</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.67</Depth>
				<Temperature>289.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.67</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>2.86</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>3.59</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>4.52</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>5.28</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>5.99</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>7.02</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>7.82</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>8.640000000000001</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>9.74</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>10.48</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>11.31</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>12.33</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>13.13</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>13.88</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>14.87</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>15.65</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>16.45</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>17.59</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>18.37</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>19.06</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>19.82</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>20.47</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>20.53</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>20.45</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>20.09</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>19.38</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>18.34</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>17.7</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>17.17</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>16.36</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>15.67</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>15.24</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>14.72</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>14.14</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>13.56</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>12.78</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>12.22</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>39</Time>
				<Depth>11.63</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>10.75</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>41</Time>
				<Depth>10.11</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>42</Time>
				<Depth>9.51</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>43</Time>
				<Depth>8.69</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>44</Time>
				<Depth>8.01</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>45</Time>
				<Depth>7.31</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>46</Time>
				<Depth>6.38</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>47</Time>
				<Depth>5.66</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>48</Time>
				<Depth>5.09</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>49</Time>
				<Depth>4.38</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>50</Time>
				<Depth>3.77</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>51</Time>
				<Depth>3.14</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>52</Time>
				<Depth>2.29</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>53</Time>
				<Depth>1.62</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>54</Time>
				<Depth>0.84</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>55</Time>
				<Depth>0.34</Depth>
				<Temperature>287.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
