<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-09-17T10:36:32</DateTime>
			<Duration>13</Duration>
			<Depth>
				<Max>2.99</Max>
				<Avg>1.9</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>180</SurfaceTime>
				<NumberInSeries>3</NumberInSeries>
				<SurfacePressure>102100</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.31</Depth>
				<Temperature>290.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.31</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>1.53</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>1.81</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>2.04</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>2.36</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>2.81</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>2.99</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>2.75</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>2.5</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>2.16</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>1.35</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>0.73</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>0.42</Depth>
				<Temperature>290.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
