<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>3</Battery>
			<DateTime>2016-01-30T12:52:06</DateTime>
			<Duration>2</Duration>
			<Depth>
				<Max>1.22</Max>
				<Avg>1.21</Avg>
			</Depth>
			<Diving>
				<DiveMode>EAN</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>66360</SurfaceTime>
				<NumberInSeries>1</NumberInSeries>
				<SurfacePressure>99900</SurfacePressure>
				<Algorithm>Suunto Technical RGBM</Algorithm>
				<Gases>
					<Gas>
						<State>Primary</State>
						<Oxygen>0.32</Oxygen>
						<Helium>0</Helium>
						<PO2>140000</PO2>
					</Gas>
					<Gas>
						<State>Secondary</State>
						<Oxygen>0.32</Oxygen>
						<Helium>0</Helium>
						<PO2>140000</PO2>
					</Gas>
					<Gas>
						<State>Off</State>
					</Gas>
				</Gases>
				<StartTissue>
					<CNS>0</CNS>
					<OTU>0</OTU>
					<Nitrogen>
						<Pressure>79000</Pressure>
						<Pressure>79000</Pressure>
						<Pressure>79000</Pressure>
						<Pressure>79000</Pressure>
						<Pressure>79000</Pressure>
						<Pressure>79000</Pressure>
						<Pressure>79000</Pressure>
						<Pressure>79000</Pressure>
						<Pressure>79000</Pressure>
					</Nitrogen>
					<RgbmNitrogen>0.9942931258106356</RgbmNitrogen>
				</StartTissue>
				<EndTissue>
					<CNS>0</CNS>
					<OTU>0</OTU>
					<OLF>0</OLF>
					<Nitrogen>
						<Pressure>79000</Pressure>
						<Pressure>79000</Pressure>
						<Pressure>79000</Pressure>
						<Pressure>79000</Pressure>
						<Pressure>79000</Pressure>
						<Pressure>79000</Pressure>
						<Pressure>79000</Pressure>
						<Pressure>79000</Pressure>
						<Pressure>79000</Pressure>
					</Nitrogen>
					<RgbmNitrogen>0.9942931258106356</RgbmNitrogen>
				</EndTissue>
			</Diving>
			<SampleInterval>20</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<GasSwitch>
						<GasNumber>1</GasNumber>
					</GasSwitch>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.22</Depth>
				<Temperature>303.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
