<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-05-26T12:31:01</DateTime>
			<Duration>92</Duration>
			<Depth>
				<Max>22.74</Max>
				<Avg>14.37</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>300</SurfaceTime>
				<NumberInSeries>15</NumberInSeries>
				<SurfacePressure>101100</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.32</Depth>
				<Temperature>299.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.32</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>2.2</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>2.94</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>3.59</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>4.19</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>4.8</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>5.43</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>6.09</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>6.78</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>7.51</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>8.24</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>8.94</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>9.699999999999999</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>10.43</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>11.18</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>11.94</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>12.7</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>13.45</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>14.22</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>15</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>15.78</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>16.58</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>17.33</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>18.02</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>18.65</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>19.2</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>19.75</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>20.32</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>20.87</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>21.37</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>21.81</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>22.1</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>22.43</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>22.68</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>22.74</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>22.72</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>22.69</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>22.63</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>39</Time>
				<Depth>22.52</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>22.36</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>41</Time>
				<Depth>22.28</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>42</Time>
				<Depth>22.25</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>43</Time>
				<Depth>22.17</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>44</Time>
				<Depth>22.13</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>45</Time>
				<Depth>22.13</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>46</Time>
				<Depth>22.2</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>47</Time>
				<Depth>22.18</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>48</Time>
				<Depth>22.2</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>49</Time>
				<Depth>22.17</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>50</Time>
				<Depth>22.16</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>51</Time>
				<Depth>22.01</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>52</Time>
				<Depth>21.73</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>53</Time>
				<Depth>21.43</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>54</Time>
				<Depth>21.08</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>55</Time>
				<Depth>20.58</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>56</Time>
				<Depth>20.07</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>57</Time>
				<Depth>19.62</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>58</Time>
				<Depth>19.43</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>59</Time>
				<Depth>19.18</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>60</Time>
				<Depth>18.87</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>61</Time>
				<Depth>18.59</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>62</Time>
				<Depth>18.33</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>63</Time>
				<Depth>18.04</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>64</Time>
				<Depth>17.72</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>65</Time>
				<Depth>17.38</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>66</Time>
				<Depth>17.01</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>67</Time>
				<Depth>16.6</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>68</Time>
				<Depth>16.2</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>69</Time>
				<Depth>15.77</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>70</Time>
				<Depth>15.17</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>71</Time>
				<Depth>14.48</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>72</Time>
				<Depth>13.67</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>73</Time>
				<Depth>12.9</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>74</Time>
				<Depth>12.12</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>75</Time>
				<Depth>11.36</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>76</Time>
				<Depth>10.62</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>77</Time>
				<Depth>9.93</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>78</Time>
				<Depth>9.15</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>79</Time>
				<Depth>8.380000000000001</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>80</Time>
				<Depth>7.64</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>81</Time>
				<Depth>6.93</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>82</Time>
				<Depth>6.23</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>83</Time>
				<Depth>5.59</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>84</Time>
				<Depth>5.03</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>85</Time>
				<Depth>4.39</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>86</Time>
				<Depth>3.74</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>87</Time>
				<Depth>3.1</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>88</Time>
				<Depth>2.51</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>89</Time>
				<Depth>1.89</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>90</Time>
				<Depth>1.25</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>91</Time>
				<Depth>0.8</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>92</Time>
				<Depth>0.49</Depth>
				<Temperature>299.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
