<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-05-26T13:03:59</DateTime>
			<Duration>38</Duration>
			<Depth>
				<Max>7.49</Max>
				<Avg>5.04</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>300</SurfaceTime>
				<NumberInSeries>23</NumberInSeries>
				<SurfacePressure>101100</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.43</Depth>
				<Temperature>299.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.43</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>2.35</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>3.11</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>3.87</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>4.55</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>5.21</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>5.83</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>6.26</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>6.64</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>6.95</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>7.23</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>7.37</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>7.45</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>7.49</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>7.47</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>7.39</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>7.3</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>7.17</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>7.04</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>6.92</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>6.8</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>6.69</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>6.55</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>6.42</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>6.22</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>6.03</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>5.64</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>5.07</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>4.5</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>3.76</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>3.22</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>2.78</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>2.44</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>2.22</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>1.8</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>1.26</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>0.79</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>0.48</Depth>
				<Temperature>299.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
