<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-08-07T13:16:29</DateTime>
			<Duration>46</Duration>
			<Depth>
				<Max>9.640000000000001</Max>
				<Avg>6.44</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>2160</SurfaceTime>
				<NumberInSeries>10</NumberInSeries>
				<SurfacePressure>100600</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.98</Depth>
				<Temperature>292.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>2.91</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>3.45</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>4.02</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>4.57</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>5.03</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>5.35</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>5.7</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>6</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>6.3</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>6.57</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>6.81</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>7.1</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>7.43</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>7.68</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>7.91</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>8.17</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>8.42</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>8.640000000000001</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>8.84</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>9.050000000000001</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>9.210000000000001</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>9.33</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>9.390000000000001</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>9.470000000000001</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>9.550000000000001</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>9.58</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>9.640000000000001</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>9.57</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>9.369999999999999</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>8.99</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>8.699999999999999</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>8.34</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>7.9</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>7.47</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>6.95</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>6.34</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>5.71</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>4.97</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>39</Time>
				<Depth>4.25</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>3.54</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>41</Time>
				<Depth>2.86</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>42</Time>
				<Depth>2.17</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>43</Time>
				<Depth>1.49</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>44</Time>
				<Depth>0.92</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>45</Time>
				<Depth>0.54</Depth>
				<Temperature>287.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>46</Time>
				<Depth>0.31</Depth>
				<Temperature>287.15</Temperature>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
