<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-09-06T12:03:51</DateTime>
			<Duration>43</Duration>
			<Depth>
				<Max>6.74</Max>
				<Avg>4.31</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>0</SurfaceTime>
				<NumberInSeries>1</NumberInSeries>
				<SurfacePressure>101000</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.41</Depth>
				<Temperature>297.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.41</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>2.23</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>2.75</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>3.12</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>3.44</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>3.71</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>3.88</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>4.01</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>4.09</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>4.25</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>4.39</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>4.5</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>4.61</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>4.74</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>4.91</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>5.01</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>5.26</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>5.48</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>5.62</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>5.78</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>5.85</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>5.9</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>6.08</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>6.39</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>6.63</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>6.73</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>6.74</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>6.57</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>6.32</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>5.96</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>5.53</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>5.1</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>4.76</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>4.41</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>4.11</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>3.77</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>3.3</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>2.74</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>39</Time>
				<Depth>2.13</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>1.47</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>41</Time>
				<Depth>0.88</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>42</Time>
				<Depth>0.66</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>43</Time>
				<Depth>0.48</Depth>
				<Temperature>297.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
