<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-08-21T09:11:51</DateTime>
			<Duration>85</Duration>
			<Depth>
				<Max>20.54</Max>
				<Avg>14.15</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>300</SurfaceTime>
				<NumberInSeries>6</NumberInSeries>
				<SurfacePressure>101500</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.75</Depth>
				<Temperature>291.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.75</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>2.94</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>4</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>4.74</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>5.46</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>6.57</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>7.43</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>8.26</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>9.41</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>10.26</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>11.1</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>12.21</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>13.02</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>13.85</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>14.92</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>15.72</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>16.42</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>17.4</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>18.07</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>18.72</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>19.56</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>20</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>20.21</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>20.24</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>20.24</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>20.4</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>20.31</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>20.17</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>20.17</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>20.28</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>20.25</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>20.18</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>20.26</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>20.36</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>20.36</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>20.32</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>20.27</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>20.31</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>39</Time>
				<Depth>20.41</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>20.38</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>41</Time>
				<Depth>20.31</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>42</Time>
				<Depth>20.25</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>43</Time>
				<Depth>20.34</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>44</Time>
				<Depth>20.32</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>45</Time>
				<Depth>20.33</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>46</Time>
				<Depth>20.47</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>47</Time>
				<Depth>20.53</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>48</Time>
				<Depth>20.47</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>49</Time>
				<Depth>20.5</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>50</Time>
				<Depth>20.54</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>51</Time>
				<Depth>20.43</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>52</Time>
				<Depth>20.41</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>53</Time>
				<Depth>20.2</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>54</Time>
				<Depth>19.59</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>55</Time>
				<Depth>19.05</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>56</Time>
				<Depth>18.48</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>57</Time>
				<Depth>17.67</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>58</Time>
				<Depth>17.09</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>59</Time>
				<Depth>16.53</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>60</Time>
				<Depth>15.78</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>61</Time>
				<Depth>15.27</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>62</Time>
				<Depth>14.74</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>63</Time>
				<Depth>14.09</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>64</Time>
				<Depth>13.58</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>65</Time>
				<Depth>13.1</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>66</Time>
				<Depth>12.29</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>67</Time>
				<Depth>11.46</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>68</Time>
				<Depth>11.04</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>69</Time>
				<Depth>10.28</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>70</Time>
				<Depth>9.93</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>71</Time>
				<Depth>9.5</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>72</Time>
				<Depth>8.710000000000001</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>73</Time>
				<Depth>8.039999999999999</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>74</Time>
				<Depth>7.41</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>75</Time>
				<Depth>6.58</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>76</Time>
				<Depth>5.95</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>77</Time>
				<Depth>5.31</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>78</Time>
				<Depth>4.64</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>79</Time>
				<Depth>4.17</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>80</Time>
				<Depth>3.66</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>81</Time>
				<Depth>2.68</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>82</Time>
				<Depth>1.91</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>83</Time>
				<Depth>1.33</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>84</Time>
				<Depth>0.75</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>85</Time>
				<Depth>0.48</Depth>
				<Temperature>287.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
