<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-06-11T11:01:18</DateTime>
			<Duration>22</Duration>
			<Depth>
				<Max>8.42</Max>
				<Avg>5.51</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>660</SurfaceTime>
				<NumberInSeries>17</NumberInSeries>
				<SurfacePressure>101300</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.88</Depth>
				<Temperature>287.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.88</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>3.58</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>4.35</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>5.1</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>6.26</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>7.04</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>7.62</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>8.130000000000001</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>8.42</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>8.17</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>8.029999999999999</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>8</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>7.85</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>7.54</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>7</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>6.34</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>5.24</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>4.32</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>3.37</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>2.01</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>0.8100000000000001</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>0.16</Depth>
				<Temperature>286.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
