<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-07-23T10:15:04</DateTime>
			<Duration>7</Duration>
			<Depth>
				<Max>1.39</Max>
				<Avg>1.23</Avg>
			</Depth>
			<Diving>
				<DiveMode>EAN</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>2700</SurfaceTime>
				<NumberInSeries>2</NumberInSeries>
				<SurfacePressure>101300</SurfacePressure>
				<Algorithm>Suunto Technical RGBM</Algorithm>
				<Gases>
					<Gas>
						<State>Primary</State>
						<Oxygen>0.32</Oxygen>
						<Helium>0</Helium>
						<PO2>140000</PO2>
					</Gas>
					<Gas>
						<State>Primary</State>
						<Oxygen>0.32</Oxygen>
						<Helium>0</Helium>
						<PO2>140000</PO2>
					</Gas>
					<Gas>
						<State>Primary</State>
						<Oxygen>0.36</Oxygen>
						<Helium>0</Helium>
						<PO2>140000</PO2>
					</Gas>
				</Gases>
				<StartTissue>
					<CNS>0.0583984375</CNS>
					<OTU>16.01953125</OTU>
					<Nitrogen>
						<Pressure>79300</Pressure>
						<Pressure>83600</Pressure>
						<Pressure>94600</Pressure>
						<Pressure>102200</Pressure>
						<Pressure>100200</Pressure>
						<Pressure>93900</Pressure>
						<Pressure>90500</Pressure>
						<Pressure>85700</Pressure>
						<Pressure>82600</Pressure>
					</Nitrogen>
					<RgbmNitrogen>0.8833752956435492</RgbmNitrogen>
				</StartTissue>
				<EndTissue>
					<CNS>0.0583984375</CNS>
					<OTU>16.01953125</OTU>
					<OLF>0.0583984375</OLF>
					<Nitrogen>
						<Pressure>79300</Pressure>
						<Pressure>83500</Pressure>
						<Pressure>94500</Pressure>
						<Pressure>102100</Pressure>
						<Pressure>100200</Pressure>
						<Pressure>93900</Pressure>
						<Pressure>90500</Pressure>
						<Pressure>85700</Pressure>
						<Pressure>82600</Pressure>
					</Nitrogen>
					<RgbmNitrogen>0.8833752956435492</RgbmNitrogen>
				</EndTissue>
			</Diving>
			<SampleInterval>20</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<GasSwitch>
						<GasNumber>1</GasNumber>
					</GasSwitch>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.22</Depth>
				<Temperature>302.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
