<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.8</Battery>
			<DateTime>2016-09-09T20:02:56</DateTime>
			<Duration>32</Duration>
			<Depth>
				<Max>3.01</Max>
				<Avg>2.43</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>0</SurfaceTime>
				<NumberInSeries>1</NumberInSeries>
				<SurfacePressure>100800</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>2.19</Depth>
				<Temperature>305.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>2.19</Depth>
				<Temperature>305.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>2.99</Depth>
				<Temperature>305.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>3.01</Depth>
				<Temperature>305.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>2.92</Depth>
				<Temperature>304.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>2.87</Depth>
				<Temperature>304.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>2.81</Depth>
				<Temperature>304.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>2.78</Depth>
				<Temperature>304.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>2.72</Depth>
				<Temperature>304.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>2.62</Depth>
				<Temperature>304.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>2.64</Depth>
				<Temperature>304.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>2.75</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>2.32</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>2.24</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>2.55</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>2.59</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>2.45</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>2.22</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>2.52</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>2.7</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>2.78</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>2.85</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>2.88</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>2.91</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>2.91</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>2.54</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>2.13</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>2.36</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>2.32</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>1.74</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>1.33</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>0.9</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>0.41</Depth>
				<Temperature>302.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
