<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-08-07T13:44:34</DateTime>
			<Duration>34</Duration>
			<Depth>
				<Max>2.88</Max>
				<Avg>1.6</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>60</SurfaceTime>
				<NumberInSeries>21</NumberInSeries>
				<SurfacePressure>100600</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.56</Depth>
				<Temperature>293.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.56</Depth>
				<Temperature>293.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>1.91</Depth>
				<Temperature>293.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>2.23</Depth>
				<Temperature>293.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>2.48</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>2.66</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>2.81</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>2.88</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>2.82</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>2.7</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>2.58</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>2.43</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>2.31</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>2.24</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>2.18</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>2.07</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>1.96</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>1.89</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>1.83</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>1.76</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>1.63</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>1.45</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>1.2</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>0.87</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>0.65</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>0.66</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>0.63</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>0.59</Depth>
				<Temperature>290.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>0.58</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>0.55</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>0.53</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>0.51</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>0.54</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>0.54</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>0.49</Depth>
				<Temperature>291.15</Temperature>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
