<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>3</Battery>
			<DateTime>2016-05-24T13:09:43</DateTime>
			<Duration>96</Duration>
			<Depth>
				<Max>27.41</Max>
				<Avg>14.01</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>180</SurfaceTime>
				<NumberInSeries>17</NumberInSeries>
				<SurfacePressure>101000</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.28</Depth>
				<Temperature>303.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.28</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>1.67</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>1.93</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>2.25</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>2.66</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>2.97</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>3.37</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>3.92</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>4.3</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>4.79</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>5.41</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>5.87</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>6.36</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>7</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>7.55</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>8.1</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>8.77</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>9.359999999999999</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>9.92</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>10.6</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>11.18</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>11.76</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>12.5</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>13.15</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>13.74</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>14.51</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>15.26</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>15.97</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>16.6</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>17.21</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>17.78</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>18.32</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>18.85</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>19.38</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>19.92</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>20.46</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>21.01</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>21.57</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>39</Time>
				<Depth>22.13</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>22.71</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>41</Time>
				<Depth>23.29</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>42</Time>
				<Depth>23.85</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>43</Time>
				<Depth>24.38</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>44</Time>
				<Depth>24.88</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>45</Time>
				<Depth>25.32</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>46</Time>
				<Depth>25.74</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>47</Time>
				<Depth>26.12</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>48</Time>
				<Depth>26.47</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>49</Time>
				<Depth>26.82</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>50</Time>
				<Depth>27.13</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>51</Time>
				<Depth>27.41</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>52</Time>
				<Depth>27.18</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>53</Time>
				<Depth>27.08</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>54</Time>
				<Depth>26.87</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>55</Time>
				<Depth>26.29</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>56</Time>
				<Depth>25.68</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>57</Time>
				<Depth>25.34</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>58</Time>
				<Depth>24.65</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>59</Time>
				<Depth>23.78</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>60</Time>
				<Depth>23.33</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>61</Time>
				<Depth>22.72</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>62</Time>
				<Depth>21.86</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>63</Time>
				<Depth>21.29</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>64</Time>
				<Depth>20.77</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>65</Time>
				<Depth>19.88</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>66</Time>
				<Depth>19.31</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>67</Time>
				<Depth>18.74</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>68</Time>
				<Depth>17.85</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>69</Time>
				<Depth>17.28</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>70</Time>
				<Depth>16.81</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>71</Time>
				<Depth>15.99</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>72</Time>
				<Depth>15.05</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>73</Time>
				<Depth>14.45</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>74</Time>
				<Depth>13.96</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>75</Time>
				<Depth>13.22</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>76</Time>
				<Depth>12.26</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>77</Time>
				<Depth>11.46</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>78</Time>
				<Depth>10.95</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>79</Time>
				<Depth>10.19</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>80</Time>
				<Depth>9.26</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>81</Time>
				<Depth>8.34</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>82</Time>
				<Depth>7.84</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>83</Time>
				<Depth>7.16</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>84</Time>
				<Depth>6.26</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>85</Time>
				<Depth>5.35</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>86</Time>
				<Depth>4.53</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>87</Time>
				<Depth>3.91</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>88</Time>
				<Depth>3.35</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>89</Time>
				<Depth>2.88</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>90</Time>
				<Depth>2.45</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>91</Time>
				<Depth>1.95</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>92</Time>
				<Depth>1.48</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>93</Time>
				<Depth>1</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>94</Time>
				<Depth>0.69</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>95</Time>
				<Depth>0.52</Depth>
				<Temperature>301.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>96</Time>
				<Depth>0.35</Depth>
				<Temperature>301.15</Temperature>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
