<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>3</Battery>
			<DateTime>2016-01-26T10:39:17</DateTime>
			<Duration>61</Duration>
			<Depth>
				<Max>16.25</Max>
				<Avg>9.52</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>180</SurfaceTime>
				<NumberInSeries>5</NumberInSeries>
				<SurfacePressure>100500</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.36</Depth>
				<Temperature>302.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.36</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>2.41</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>3.25</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>4.02</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>4.71</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>5.33</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>5.92</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>6.4</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>6.83</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>7.1</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>6.96</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>6.85</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>6.9</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>6.9</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>6.95</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>7.17</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>7.6</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>8.16</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>8.75</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>9.44</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>10.09</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>10.74</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>11.4</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>12.09</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>12.72</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>13.33</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>13.92</Depth>
				<Temperature>301.15</Temperature>
				<Events>
					<Notify>
						<Type>Depth</Type>
					</Notify>
				</Events>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>14.53</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>15.19</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>15.56</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>15.8</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>16.07</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>16.23</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>16.25</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>16.17</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>15.99</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>15.78</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>15.58</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>39</Time>
				<Depth>15.37</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>15.03</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>41</Time>
				<Depth>14.66</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>42</Time>
				<Depth>14.26</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>43</Time>
				<Depth>13.73</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>44</Time>
				<Depth>13.17</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>45</Time>
				<Depth>12.57</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>46</Time>
				<Depth>11.95</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>47</Time>
				<Depth>11.35</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>48</Time>
				<Depth>10.75</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>49</Time>
				<Depth>10.08</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>50</Time>
				<Depth>9.390000000000001</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>51</Time>
				<Depth>8.630000000000001</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>52</Time>
				<Depth>7.87</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>53</Time>
				<Depth>7.05</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>54</Time>
				<Depth>6.2</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>55</Time>
				<Depth>5.33</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>56</Time>
				<Depth>4.42</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>57</Time>
				<Depth>3.43</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>58</Time>
				<Depth>2.45</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>59</Time>
				<Depth>1.56</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>60</Time>
				<Depth>0.79</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>61</Time>
				<Depth>0.42</Depth>
				<Temperature>301.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
