<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-06-19T09:09:04</DateTime>
			<Duration>43</Duration>
			<Depth>
				<Max>13.55</Max>
				<Avg>7.42</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>360</SurfaceTime>
				<NumberInSeries>2</NumberInSeries>
				<SurfacePressure>102900</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.85</Depth>
				<Temperature>288.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.85</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>3.57</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>4.37</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>5.12</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>6.1</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>6.69</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>7.1</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>7.24</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>7.12</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>6.99</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>6.77</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>6.87</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>6.86</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>6.94</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>6.72</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>7.09</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>8.01</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>8.68</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>9.449999999999999</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>10.48</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>11.22</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>11.98</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>12.67</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>12.87</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>13.15</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>13.5</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>13.55</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>13.08</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>12.39</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>11.2</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>9.84</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>8.69</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>7.45</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>6.96</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>5.86</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>5.16</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>4.51</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>3.83</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>39</Time>
				<Depth>2.89</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>2.25</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>41</Time>
				<Depth>1.59</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>42</Time>
				<Depth>0.53</Depth>
				<Temperature>286.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>43</Time>
				<Depth>0.18</Depth>
				<Temperature>286.15</Temperature>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
