<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-09-17T11:43:48</DateTime>
			<Duration>32</Duration>
			<Depth>
				<Max>8.42</Max>
				<Avg>4.7</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>720</SurfaceTime>
				<NumberInSeries>17</NumberInSeries>
				<SurfacePressure>102100</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.43</Depth>
				<Temperature>290.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.47</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>2.04</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>2.35</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>2.72</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>2.85</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>2.95</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>3.14</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>3.39</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>3.66</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>4.05</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>4.4</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>4.84</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>5.41</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>5.86</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>6.29</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>6.66</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>7.11</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>7.63</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>8.17</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>8.42</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>8.390000000000001</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>8.17</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>7.66</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>6.87</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>5.86</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>5.2</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>4.82</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>3.7</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>2.91</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>2.17</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>1.09</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>0.37</Depth>
				<Temperature>289.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
