<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-06-19T09:56:30</DateTime>
			<Duration>64</Duration>
			<Depth>
				<Max>14.17</Max>
				<Avg>8.15</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>540</SurfaceTime>
				<NumberInSeries>9</NumberInSeries>
				<SurfacePressure>102900</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>2.75</Depth>
				<Temperature>288.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>2.75</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>4.44</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>5.23</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>5.83</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>6.36</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>6.41</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>6.54</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>6.58</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>6.5</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>6.39</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>6.47</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>6.33</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>6.33</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>6.38</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>6.44</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>6.34</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>6.34</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>6.45</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>6.56</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>6.56</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>6.39</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>6.34</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>6.36</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>6.68</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>7.14</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>7.72</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>8.58</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>9.210000000000001</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>9.810000000000001</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>10.6</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>11.26</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>11.91</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>12.73</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>13.38</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>13.79</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>14.16</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>14.15</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>14.17</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>39</Time>
				<Depth>14.14</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>14.11</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>41</Time>
				<Depth>13.95</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>42</Time>
				<Depth>13.64</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>43</Time>
				<Depth>13.35</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>44</Time>
				<Depth>13.14</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>45</Time>
				<Depth>12.53</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>46</Time>
				<Depth>12.19</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>47</Time>
				<Depth>11.62</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>48</Time>
				<Depth>10.85</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>49</Time>
				<Depth>10.27</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>50</Time>
				<Depth>9.720000000000001</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>51</Time>
				<Depth>8.970000000000001</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>52</Time>
				<Depth>8.48</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>53</Time>
				<Depth>7.95</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>54</Time>
				<Depth>7.13</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>55</Time>
				<Depth>6.49</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>56</Time>
				<Depth>5.71</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>57</Time>
				<Depth>4.98</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>58</Time>
				<Depth>4.56</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>59</Time>
				<Depth>3.85</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>60</Time>
				<Depth>3.06</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>61</Time>
				<Depth>2.42</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>62</Time>
				<Depth>1.77</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>63</Time>
				<Depth>0.89</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>64</Time>
				<Depth>0.32</Depth>
				<Temperature>286.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
