<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-06-18T15:58:11</DateTime>
			<Duration>47</Duration>
			<Depth>
				<Max>20.85</Max>
				<Avg>11.53</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>240</SurfaceTime>
				<NumberInSeries>16</NumberInSeries>
				<SurfacePressure>102200</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.51</Depth>
				<Temperature>290.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.51</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>2.79</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>3.8</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>4.52</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>5.27</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>6.34</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>7.16</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>7.93</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>8.949999999999999</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>9.74</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>10.55</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>11.68</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>12.54</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>13.42</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>14.59</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>15.5</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>16.42</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>17.62</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>18.55</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>19.55</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>20.55</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>20.69</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>20.85</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>20.75</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>20.49</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>20.16</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>19.2</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>18.38</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>17.56</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>16.52</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>15.7</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>14.92</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>13.83</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>13.01</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>12.16</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>10.99</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>10.03</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>8.84</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>39</Time>
				<Depth>8.07</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>7.46</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>41</Time>
				<Depth>6.61</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>42</Time>
				<Depth>5.39</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>43</Time>
				<Depth>4.44</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>44</Time>
				<Depth>3.4</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>45</Time>
				<Depth>2.16</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>46</Time>
				<Depth>1.28</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>47</Time>
				<Depth>0.45</Depth>
				<Temperature>286.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
