<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-05-12T13:42:45</DateTime>
			<Duration>64</Duration>
			<Depth>
				<Max>20.48</Max>
				<Avg>11.24</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>780</SurfaceTime>
				<NumberInSeries>24</NumberInSeries>
				<SurfacePressure>101300</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.76</Depth>
				<Temperature>297.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.76</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>3.03</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>3.96</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>4.73</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>4.63</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>5.19</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>6.09</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>6.78</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>7.57</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>8.779999999999999</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>8.84</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>9.279999999999999</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>10.15</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>10.79</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>11.34</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>12.04</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>12.56</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>12.99</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>13.63</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>14.19</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>14.73</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>15.55</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>16.17</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>16.81</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>17.71</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>18.37</Depth>
				<Temperature>297.15</Temperature>
				<Events>
					<Notify>
						<Type>Depth</Type>
					</Notify>
				</Events>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>19.06</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>19.62</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>20.3</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>20.39</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>20.48</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>20.39</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>19.98</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>19.25</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>18.05</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>17.72</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>17.76</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>17.26</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>39</Time>
				<Depth>16.83</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>15.95</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>41</Time>
				<Depth>14.64</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>42</Time>
				<Depth>14.21</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>43</Time>
				<Depth>14.14</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>44</Time>
				<Depth>13.63</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>45</Time>
				<Depth>13.21</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>46</Time>
				<Depth>12.31</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>47</Time>
				<Depth>11.03</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>48</Time>
				<Depth>10.64</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>49</Time>
				<Depth>10.59</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>50</Time>
				<Depth>10.04</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>51</Time>
				<Depth>9.51</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>52</Time>
				<Depth>8.49</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>53</Time>
				<Depth>7.15</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>54</Time>
				<Depth>6.59</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>55</Time>
				<Depth>6.56</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>56</Time>
				<Depth>6.01</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>57</Time>
				<Depth>5.47</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>58</Time>
				<Depth>4.65</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>59</Time>
				<Depth>3.12</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>60</Time>
				<Depth>2.27</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>61</Time>
				<Depth>1.88</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>62</Time>
				<Depth>1.61</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>63</Time>
				<Depth>0.85</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>64</Time>
				<Depth>0.14</Depth>
				<Temperature>297.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
