<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-01-30T15:43:15</DateTime>
			<Duration>44</Duration>
			<Depth>
				<Max>7.36</Max>
				<Avg>4.18</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>60</SurfaceTime>
				<NumberInSeries>9</NumberInSeries>
				<SurfacePressure>100200</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.27</Depth>
				<Temperature>302.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.27</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>1.79</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>1.81</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>1.84</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>2.03</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>2.08</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>2.34</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>2.7</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>2.92</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>3.06</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>3.26</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>3.54</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>3.7</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>3.91</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>4.22</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>4.44</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>4.57</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>4.79</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>5.06</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>5.24</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>5.5</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>5.75</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>5.94</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>6.18</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>6.4</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>6.62</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>6.81</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>7.02</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>7.15</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>7.36</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>7.11</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>7.06</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>6.67</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>6.19</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>5.68</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>5.04</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>4.22</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>3.62</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>39</Time>
				<Depth>2.94</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>2.28</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>41</Time>
				<Depth>1.92</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>42</Time>
				<Depth>1.49</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>43</Time>
				<Depth>0.55</Depth>
				<Temperature>302.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>44</Time>
				<Depth>0.08</Depth>
				<Temperature>302.15</Temperature>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
