<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-08-07T11:00:36</DateTime>
			<Duration>50</Duration>
			<Depth>
				<Max>16.54</Max>
				<Avg>8.859999999999999</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>0</SurfaceTime>
				<NumberInSeries>1</NumberInSeries>
				<SurfacePressure>100600</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.38</Depth>
				<Temperature>292.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.38</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>2.39</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>3.29</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>4.12</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>4.95</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>5.78</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>6.61</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>7.45</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>8.32</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>9.17</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>10.05</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>10.92</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>11.79</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>12.7</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>13.56</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>14.34</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>15.27</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>15.96</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>16.39</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>16.54</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>16.4</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>16.45</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>16.37</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>16.18</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>15.82</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>15.31</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>14.7</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>14.07</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>13.44</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>12.76</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>12.01</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>11.21</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>10.4</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>9.560000000000001</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>8.73</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>7.86</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>7</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>6.15</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>39</Time>
				<Depth>5.5</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>4.82</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>41</Time>
				<Depth>4.19</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>42</Time>
				<Depth>3.6</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>43</Time>
				<Depth>2.95</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>44</Time>
				<Depth>2.26</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>45</Time>
				<Depth>1.56</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>46</Time>
				<Depth>1</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>47</Time>
				<Depth>0.72</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>48</Time>
				<Depth>0.59</Depth>
				<Temperature>287.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>49</Time>
				<Depth>0.52</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>50</Time>
				<Depth>0.29</Depth>
				<Temperature>287.15</Temperature>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
