<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>3</Battery>
			<DateTime>2016-01-26T10:53:53</DateTime>
			<Duration>61</Duration>
			<Depth>
				<Max>3.24</Max>
				<Avg>2.61</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>420</SurfaceTime>
				<NumberInSeries>7</NumberInSeries>
				<SurfacePressure>100500</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.24</Depth>
				<Temperature>302.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.24</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>1.95</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>2.54</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>2.85</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>2.99</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>3.06</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>3.1</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>3.18</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>3.18</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>3.18</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>3.24</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>3.23</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>3.18</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>3.14</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>3.15</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>3.11</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>3.05</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>3.01</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>3.04</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>3.05</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>3.02</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>2.98</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>3</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>3.09</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>3.13</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>3.05</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>2.86</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>2.79</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>2.84</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>2.89</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>2.83</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>2.76</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>2.76</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>2.81</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>2.79</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>2.8</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>2.79</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>2.78</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>39</Time>
				<Depth>2.87</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>2.84</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>41</Time>
				<Depth>2.66</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>42</Time>
				<Depth>2.42</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>43</Time>
				<Depth>2.34</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>44</Time>
				<Depth>2.3</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>45</Time>
				<Depth>2.29</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>46</Time>
				<Depth>2.36</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>47</Time>
				<Depth>2.39</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>48</Time>
				<Depth>2.41</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>49</Time>
				<Depth>2.38</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>50</Time>
				<Depth>2.4</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>51</Time>
				<Depth>2.38</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>52</Time>
				<Depth>2.36</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>53</Time>
				<Depth>2.36</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>54</Time>
				<Depth>2.27</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>55</Time>
				<Depth>2.26</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>56</Time>
				<Depth>2.14</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>57</Time>
				<Depth>1.89</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>58</Time>
				<Depth>1.56</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>59</Time>
				<Depth>1.08</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>60</Time>
				<Depth>0.59</Depth>
				<Temperature>301.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>61</Time>
				<Depth>0.32</Depth>
				<Temperature>301.15</Temperature>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
