<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-09-06T13:00:05</DateTime>
			<Duration>62</Duration>
			<Depth>
				<Max>8.02</Max>
				<Avg>5.52</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>360</SurfaceTime>
				<NumberInSeries>6</NumberInSeries>
				<SurfacePressure>101000</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.38</Depth>
				<Temperature>297.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.38</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>2.45</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>3.33</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>4.15</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>4.84</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>5.55</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>6.21</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>6.78</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>7.31</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>7.55</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>7.75</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>7.87</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>7.99</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>8.02</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>8.02</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>7.99</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>7.91</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>7.74</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>7.66</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>7.58</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>7.47</Depth>
				<Temperature>296.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>7.49</Depth>
				<Temperature>296.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>7.48</Depth>
				<Temperature>296.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>7.26</Depth>
				<Temperature>296.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>7.06</Depth>
				<Temperature>296.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>6.89</Depth>
				<Temperature>296.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>6.83</Depth>
				<Temperature>296.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>6.84</Depth>
				<Temperature>296.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>6.81</Depth>
				<Temperature>296.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>6.6</Depth>
				<Temperature>296.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>6.35</Depth>
				<Temperature>296.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>6.16</Depth>
				<Temperature>296.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>6.04</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>5.99</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>6</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>5.86</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>5.74</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>5.61</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>39</Time>
				<Depth>5.53</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>5.45</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>41</Time>
				<Depth>5.34</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>42</Time>
				<Depth>5.33</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>43</Time>
				<Depth>5.31</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>44</Time>
				<Depth>5.27</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>45</Time>
				<Depth>5.23</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>46</Time>
				<Depth>5.23</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>47</Time>
				<Depth>5.25</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>48</Time>
				<Depth>5.22</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>49</Time>
				<Depth>5.23</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>50</Time>
				<Depth>5.1</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>51</Time>
				<Depth>4.9</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>52</Time>
				<Depth>4.68</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>53</Time>
				<Depth>4.34</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>54</Time>
				<Depth>3.95</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>55</Time>
				<Depth>3.5</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>56</Time>
				<Depth>3.07</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>57</Time>
				<Depth>2.67</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>58</Time>
				<Depth>2.17</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>59</Time>
				<Depth>1.54</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>60</Time>
				<Depth>0.94</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>61</Time>
				<Depth>0.58</Depth>
				<Temperature>297.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>62</Time>
				<Depth>0.44</Depth>
				<Temperature>297.15</Temperature>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
