<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-06-19T09:21:21</DateTime>
			<Duration>42</Duration>
			<Depth>
				<Max>19.22</Max>
				<Avg>10.07</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>300</SurfaceTime>
				<NumberInSeries>5</NumberInSeries>
				<SurfacePressure>102900</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>2.1</Depth>
				<Temperature>288.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>2.1</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>3.4</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>4.51</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>5.34</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>6.2</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>7.38</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>8.27</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>9.130000000000001</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>10.28</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>11.15</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>12.04</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>13.25</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>14.14</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>15.05</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>16.37</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>17.35</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>18.33</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>19.11</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>19.22</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>18.82</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>17.79</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>16.98</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>16.23</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>15.09</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>14.32</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>13.53</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>12.5</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>11.72</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>10.93</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>9.85</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>9.029999999999999</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>8.220000000000001</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>7.18</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>6.47</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>5.63</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>4.5</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>3.74</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>3.1</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>39</Time>
				<Depth>2.21</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>1.5</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>41</Time>
				<Depth>0.79</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>42</Time>
				<Depth>0.42</Depth>
				<Temperature>285.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
