<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-06-19T09:42:52</DateTime>
			<Duration>53</Duration>
			<Depth>
				<Max>15.01</Max>
				<Avg>8.66</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>120</SurfaceTime>
				<NumberInSeries>7</NumberInSeries>
				<SurfacePressure>102900</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.25</Depth>
				<Temperature>288.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.25</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>2.28</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>3.04</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>3.58</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>4.14</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>4.93</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>5.57</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>6.2</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>7.01</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>7.63</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>8.220000000000001</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>9</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>9.58</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>10.02</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>10.71</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>11.25</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>11.82</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>12.53</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>12.93</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>13.41</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>13.74</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>13.91</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>14.18</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>14.5</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>14.55</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>14.66</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>14.48</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>15.01</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>14.96</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>14.48</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>13.69</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>13.17</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>12.72</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>12.05</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>11.46</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>10.84</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>9.98</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>9.359999999999999</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>39</Time>
				<Depth>8.77</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>7.95</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>41</Time>
				<Depth>7.42</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>42</Time>
				<Depth>6.79</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>43</Time>
				<Depth>5.99</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>44</Time>
				<Depth>5.42</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>45</Time>
				<Depth>4.95</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>46</Time>
				<Depth>4.38</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>47</Time>
				<Depth>3.93</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>48</Time>
				<Depth>3.45</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>49</Time>
				<Depth>2.76</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>50</Time>
				<Depth>2.14</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>51</Time>
				<Depth>1.5</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>52</Time>
				<Depth>0.69</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>53</Time>
				<Depth>0.44</Depth>
				<Temperature>287.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
