<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>3</Battery>
			<DateTime>2016-01-25T13:27:49</DateTime>
			<Duration>43</Duration>
			<Depth>
				<Max>10.82</Max>
				<Avg>6.98</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>240</SurfaceTime>
				<NumberInSeries>8</NumberInSeries>
				<SurfacePressure>100500</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.85</Depth>
				<Temperature>303.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.85</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>3.09</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>3.51</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>3.79</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>4.11</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>4.54</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>5.17</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>5.75</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>6.37</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>7.23</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>7.81</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>8.35</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>9.08</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>9.640000000000001</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>10.15</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>10.44</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>10.62</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>10.72</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>10.82</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>10.76</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>10.38</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>10.26</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>10.16</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>10.19</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>10.13</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>10.11</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>10.17</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>10</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>9.869999999999999</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>9.49</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>8.710000000000001</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>8.07</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>7.35</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>6.34</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>5.61</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>4.95</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>4.24</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>3.37</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>39</Time>
				<Depth>2.72</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>2.13</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>41</Time>
				<Depth>1.34</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>42</Time>
				<Depth>0.7</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>43</Time>
				<Depth>0.17</Depth>
				<Temperature>302.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
