<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>3</Battery>
			<DateTime>2016-01-28T12:23:45</DateTime>
			<Duration>41</Duration>
			<Depth>
				<Max>10.37</Max>
				<Avg>6.09</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>240</SurfaceTime>
				<NumberInSeries>10</NumberInSeries>
				<SurfacePressure>100500</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.26</Depth>
				<Temperature>302.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.26</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>2.06</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>2.65</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>3.14</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>3.67</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>4.2</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>4.68</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>5.48</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>5.83</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>6.21</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>6.68</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>7.21</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>7.88</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>8.539999999999999</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>9.27</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>9.789999999999999</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>10.1</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>10.28</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>10.33</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>10.37</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>10.29</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>10.2</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>10.13</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>9.85</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>9.449999999999999</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>8.960000000000001</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>8.369999999999999</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>7.82</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>7.21</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>6.53</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>5.83</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>4.99</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>4.32</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>3.89</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>3.5</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>2.98</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>2.31</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>1.55</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>39</Time>
				<Depth>1</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>0.65</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>41</Time>
				<Depth>0.43</Depth>
				<Temperature>302.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
