<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-08-07T11:46:20</DateTime>
			<Duration>102</Duration>
			<Depth>
				<Max>21.9</Max>
				<Avg>14.73</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>360</SurfaceTime>
				<NumberInSeries>5</NumberInSeries>
				<SurfacePressure>100600</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.23</Depth>
				<Temperature>294.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.23</Depth>
				<Temperature>294.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>2.16</Depth>
				<Temperature>294.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>2.98</Depth>
				<Temperature>294.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>3.76</Depth>
				<Temperature>293.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>4.54</Depth>
				<Temperature>293.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>5.34</Depth>
				<Temperature>293.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>6.17</Depth>
				<Temperature>293.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>7.04</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>7.94</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>8.859999999999999</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>9.810000000000001</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>10.75</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>11.69</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>12.62</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>13.6</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>14.6</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>15.58</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>16.48</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>17.32</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>18.13</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>18.91</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>19.6</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>20.36</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>20.77</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>20.97</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>21.2</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>21.39</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>21.53</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>21.52</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>21.46</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>21.53</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>21.65</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>21.69</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>21.77</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>21.83</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>21.9</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>21.85</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>21.8</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>39</Time>
				<Depth>21.79</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>21.78</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>41</Time>
				<Depth>21.79</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>42</Time>
				<Depth>21.79</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>43</Time>
				<Depth>21.79</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>44</Time>
				<Depth>21.82</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>45</Time>
				<Depth>21.83</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>46</Time>
				<Depth>21.82</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>47</Time>
				<Depth>21.81</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>48</Time>
				<Depth>21.79</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>49</Time>
				<Depth>21.79</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>50</Time>
				<Depth>21.77</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>51</Time>
				<Depth>21.79</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>52</Time>
				<Depth>21.76</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>53</Time>
				<Depth>21.72</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>54</Time>
				<Depth>21.74</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>55</Time>
				<Depth>21.73</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>56</Time>
				<Depth>21.7</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>57</Time>
				<Depth>21.64</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>58</Time>
				<Depth>21.3</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>59</Time>
				<Depth>21.06</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>60</Time>
				<Depth>20.88</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>61</Time>
				<Depth>20.73</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>62</Time>
				<Depth>20.57</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>63</Time>
				<Depth>20.33</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>64</Time>
				<Depth>20</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>65</Time>
				<Depth>19.6</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>66</Time>
				<Depth>19.15</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>67</Time>
				<Depth>18.69</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>68</Time>
				<Depth>18.28</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>69</Time>
				<Depth>17.87</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>70</Time>
				<Depth>17.41</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>71</Time>
				<Depth>16.89</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>72</Time>
				<Depth>16.37</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>73</Time>
				<Depth>15.82</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>74</Time>
				<Depth>15.21</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>75</Time>
				<Depth>14.58</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>76</Time>
				<Depth>13.95</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>77</Time>
				<Depth>13.33</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>78</Time>
				<Depth>12.72</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>79</Time>
				<Depth>12.1</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>80</Time>
				<Depth>11.49</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>81</Time>
				<Depth>10.86</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>82</Time>
				<Depth>10.25</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>83</Time>
				<Depth>9.67</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>84</Time>
				<Depth>9.109999999999999</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>85</Time>
				<Depth>8.619999999999999</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>86</Time>
				<Depth>8.109999999999999</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>87</Time>
				<Depth>7.54</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>88</Time>
				<Depth>7.01</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>89</Time>
				<Depth>6.52</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>90</Time>
				<Depth>6.08</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>91</Time>
				<Depth>5.65</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>92</Time>
				<Depth>5.22</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>93</Time>
				<Depth>4.8</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>94</Time>
				<Depth>4.33</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>95</Time>
				<Depth>3.82</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>96</Time>
				<Depth>3.24</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>97</Time>
				<Depth>2.61</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>98</Time>
				<Depth>1.93</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>99</Time>
				<Depth>1.25</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>100</Time>
				<Depth>0.91</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>101</Time>
				<Depth>0.63</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>102</Time>
				<Depth>0.39</Depth>
				<Temperature>287.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
