<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-09-06T13:15:11</DateTime>
			<Duration>19</Duration>
			<Depth>
				<Max>5</Max>
				<Avg>3.15</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>240</SurfaceTime>
				<NumberInSeries>9</NumberInSeries>
				<SurfacePressure>101000</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.7</Depth>
				<Temperature>297.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.7</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>2.78</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>3.74</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>4.4</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>4.77</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>4.98</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>5</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>4.88</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>4.7</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>4.43</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>4.07</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>3.63</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>3.14</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>2.61</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>2.02</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>1.36</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>0.8</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>0.55</Depth>
				<Temperature>297.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>0.34</Depth>
				<Temperature>297.15</Temperature>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
