<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>3</Battery>
			<DateTime>2016-02-03T12:47:39</DateTime>
			<Duration>68</Duration>
			<Depth>
				<Max>19.65</Max>
				<Avg>12.45</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>300</SurfaceTime>
				<NumberInSeries>11</NumberInSeries>
				<SurfacePressure>100500</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
					<Notify>
						<Type>Tank Pressure</Type>
						<Active>false</Active>
					</Notify>
					<Warning>
						<Type>Tank Pressure</Type>
						<Active>false</Active>
					</Warning>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.51</Depth>
				<Temperature>302.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.51</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>2.58</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>3.5</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>4.4</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>5.28</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>6.18</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>7.09</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>7.97</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>8.869999999999999</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>9.76</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>10.66</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>11.54</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>12.45</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>13.38</Depth>
				<Temperature>302.15</Temperature>
				<Events>
					<Notify>
						<Type>Depth</Type>
					</Notify>
				</Events>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>14.24</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>15.22</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>16.04</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>16.84</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>17.6</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>18.3</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>18.94</Depth>
				<Temperature>302.15</Temperature>
				<Events>
					<Notify>
						<Type>Depth</Type>
					</Notify>
				</Events>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>19.18</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>19.45</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>19.6</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>19.53</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>19.5</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>19.59</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>19.61</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>19.58</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>19.58</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>19.61</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>19.65</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>19.57</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>19.48</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>19.39</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>19.26</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>19.09</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>18.87</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>39</Time>
				<Depth>18.44</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>18.02</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>41</Time>
				<Depth>17.56</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>42</Time>
				<Depth>17.07</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>43</Time>
				<Depth>16.3</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>44</Time>
				<Depth>15.58</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>45</Time>
				<Depth>15.15</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>46</Time>
				<Depth>14.67</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>47</Time>
				<Depth>14.11</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>48</Time>
				<Depth>13.5</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>49</Time>
				<Depth>12.85</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>50</Time>
				<Depth>12.17</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>51</Time>
				<Depth>11.54</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>52</Time>
				<Depth>10.87</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>53</Time>
				<Depth>10.21</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>54</Time>
				<Depth>9.529999999999999</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>55</Time>
				<Depth>8.859999999999999</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>56</Time>
				<Depth>8.289999999999999</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>57</Time>
				<Depth>7.79</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>58</Time>
				<Depth>7.21</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>59</Time>
				<Depth>6.55</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>60</Time>
				<Depth>5.88</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>61</Time>
				<Depth>5.26</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>62</Time>
				<Depth>4.65</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>63</Time>
				<Depth>3.95</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>64</Time>
				<Depth>3.19</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>65</Time>
				<Depth>2.44</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>66</Time>
				<Depth>1.52</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>67</Time>
				<Depth>0.76</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>68</Time>
				<Depth>0.4</Depth>
				<Temperature>302.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
