<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>3</Battery>
			<DateTime>2016-02-06T10:18:24</DateTime>
			<Duration>35</Duration>
			<Depth>
				<Max>10.07</Max>
				<Avg>6.55</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>360</SurfaceTime>
				<NumberInSeries>6</NumberInSeries>
				<SurfacePressure>100200</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
					<Notify>
						<Type>Tank Pressure</Type>
						<Active>false</Active>
					</Notify>
					<Warning>
						<Type>Tank Pressure</Type>
						<Active>false</Active>
					</Warning>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.73</Depth>
				<Temperature>302.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.73</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>2.61</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>3.58</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>4</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>4.17</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>5.05</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>5.33</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>5.81</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>6.45</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>6.76</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>7.27</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>7.99</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>8.52</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>9.039999999999999</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>9.32</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>9.65</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>9.779999999999999</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>9.9</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>9.949999999999999</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>10.03</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>10.07</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>10.04</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>9.93</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>9.42</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>8.74</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>8.310000000000001</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>7.67</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>6.75</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>5.99</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>5.18</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>4.09</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>3.01</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>1.81</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>1.11</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>0.35</Depth>
				<Temperature>302.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
