<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-05-14T12:29:36</DateTime>
			<Duration>54</Duration>
			<Depth>
				<Max>8.4</Max>
				<Avg>6.44</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>60</SurfaceTime>
				<NumberInSeries>17</NumberInSeries>
				<SurfacePressure>101300</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.6</Depth>
				<Temperature>302.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.6</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>2.93</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>3.72</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>4.39</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>5.22</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>5.88</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>6.52</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>7.34</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>7.73</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>7.77</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>8.08</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>8.18</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>8.27</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>8.24</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>8.26</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>8.26</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>8.24</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>8.26</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>8.300000000000001</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>8.369999999999999</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>8.4</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>8.380000000000001</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>8.35</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>8.32</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>8.380000000000001</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>8.34</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>8.32</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>8.279999999999999</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>8.15</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>8.01</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>7.89</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>7.8</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>7.7</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>7.6</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>7.46</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>7.34</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>7.37</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>7.31</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>39</Time>
				<Depth>7.18</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>7.07</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>41</Time>
				<Depth>7</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>42</Time>
				<Depth>6.82</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>43</Time>
				<Depth>6.52</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>44</Time>
				<Depth>5.96</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>45</Time>
				<Depth>5.45</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>46</Time>
				<Depth>4.97</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>47</Time>
				<Depth>4.34</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>48</Time>
				<Depth>3.89</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>49</Time>
				<Depth>3.47</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>50</Time>
				<Depth>2.7</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>51</Time>
				<Depth>1.96</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>52</Time>
				<Depth>1.32</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>53</Time>
				<Depth>0.54</Depth>
				<Temperature>301.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>54</Time>
				<Depth>0.14</Depth>
				<Temperature>301.15</Temperature>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
