<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-08-07T13:41:31</DateTime>
			<Duration>39</Duration>
			<Depth>
				<Max>3.86</Max>
				<Avg>3.05</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>120</SurfaceTime>
				<NumberInSeries>19</NumberInSeries>
				<SurfacePressure>100600</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.25</Depth>
				<Temperature>293.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.25</Depth>
				<Temperature>293.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>1.9</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>2.39</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>2.75</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>3.09</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>3.42</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>3.71</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>3.77</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>3.81</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>3.86</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>3.83</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>3.83</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>3.81</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>3.78</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>3.79</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>3.78</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>3.69</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>3.62</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>3.64</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>3.65</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>3.61</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>3.62</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>3.66</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>3.71</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>3.76</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>3.76</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>3.72</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>3.66</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>3.54</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>3.34</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>3.1</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>2.82</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>2.49</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>2.1</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>1.67</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>1.2</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>0.84</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>0.62</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>39</Time>
				<Depth>0.47</Depth>
				<Temperature>289.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
