<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>3</Battery>
			<DateTime>2016-02-03T12:36:02</DateTime>
			<Duration>67</Duration>
			<Depth>
				<Max>20.38</Max>
				<Avg>12.15</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>300</SurfaceTime>
				<NumberInSeries>9</NumberInSeries>
				<SurfacePressure>100500</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
					<Notify>
						<Type>Tank Pressure</Type>
						<Active>false</Active>
					</Notify>
					<Warning>
						<Type>Tank Pressure</Type>
						<Active>false</Active>
					</Warning>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.23</Depth>
				<Temperature>302.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.23</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>2.31</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>3.22</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>4.07</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>4.94</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>5.8</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>6.64</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>7.48</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>8.369999999999999</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>9.25</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>10.11</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>11</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>11.85</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>12.69</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>13.5</Depth>
				<Temperature>302.15</Temperature>
				<Events>
					<Notify>
						<Type>Depth</Type>
					</Notify>
				</Events>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>14.25</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>14.98</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>15.57</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>16.21</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>16.83</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>17.36</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>17.9</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>18.51</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>18.88</Depth>
				<Temperature>302.15</Temperature>
				<Events>
					<Notify>
						<Type>Depth</Type>
					</Notify>
				</Events>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>19.13</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>19.3</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>19.86</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>20.28</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>20.38</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>20.32</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>19.98</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>19.75</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>19.69</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>19.59</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>19.34</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>19.03</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>18.78</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>18.44</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>39</Time>
				<Depth>18</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>17.46</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>41</Time>
				<Depth>16.93</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>42</Time>
				<Depth>16.37</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>43</Time>
				<Depth>15.83</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>44</Time>
				<Depth>15.24</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>45</Time>
				<Depth>14.68</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>46</Time>
				<Depth>14.14</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>47</Time>
				<Depth>13.66</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>48</Time>
				<Depth>13.14</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>49</Time>
				<Depth>12.58</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>50</Time>
				<Depth>11.98</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>51</Time>
				<Depth>11.34</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>52</Time>
				<Depth>10.69</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>53</Time>
				<Depth>10.01</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>54</Time>
				<Depth>9.33</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>55</Time>
				<Depth>8.6</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>56</Time>
				<Depth>7.86</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>57</Time>
				<Depth>7.12</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>58</Time>
				<Depth>6.45</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>59</Time>
				<Depth>5.76</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>60</Time>
				<Depth>5.17</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>61</Time>
				<Depth>4.44</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>62</Time>
				<Depth>3.65</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>63</Time>
				<Depth>2.89</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>64</Time>
				<Depth>2.1</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>65</Time>
				<Depth>1.32</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>66</Time>
				<Depth>0.66</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>67</Time>
				<Depth>0.33</Depth>
				<Temperature>302.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
