<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-05-19T12:35:42</DateTime>
			<Duration>142</Duration>
			<Depth>
				<Max>21.41</Max>
				<Avg>16.1</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>240</SurfaceTime>
				<NumberInSeries>3</NumberInSeries>
				<SurfacePressure>101000</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.7</Depth>
				<Temperature>303.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.7</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>2.24</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>2.94</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>3.6</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>4.79</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>4.9</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>5.12</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>6.05</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>6.69</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>7.62</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>8.199999999999999</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>8.359999999999999</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>8.949999999999999</Depth>
				<Temperature>303.15</Temperature>
				<Events>
					<Notify>
						<Type>Depth</Type>
					</Notify>
				</Events>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>9.960000000000001</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>10.81</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>11.78</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>12.35</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>12.6</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>13.26</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>14.04</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>15.14</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>15.95</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>16.6</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>17.36</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>17.86</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>18.57</Depth>
				<Temperature>300.15</Temperature>
				<Events>
					<Notify>
						<Type>Depth</Type>
					</Notify>
				</Events>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>19.48</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>20.19</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>20.82</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>21.22</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>21.39</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>21.33</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>21.18</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>20.96</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>20.93</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>20.93</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>20.99</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>21.21</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>39</Time>
				<Depth>21.34</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>21.39</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>41</Time>
				<Depth>21.41</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>42</Time>
				<Depth>21.39</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>43</Time>
				<Depth>21.4</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>44</Time>
				<Depth>21.39</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>45</Time>
				<Depth>20.96</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>46</Time>
				<Depth>20.71</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>47</Time>
				<Depth>20.7</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>48</Time>
				<Depth>20.73</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>49</Time>
				<Depth>20.72</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>50</Time>
				<Depth>20.73</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>51</Time>
				<Depth>20.72</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>52</Time>
				<Depth>20.73</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>53</Time>
				<Depth>20.73</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>54</Time>
				<Depth>20.73</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>55</Time>
				<Depth>20.73</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>56</Time>
				<Depth>20.73</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>57</Time>
				<Depth>20.72</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>58</Time>
				<Depth>20.71</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>59</Time>
				<Depth>20.73</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>60</Time>
				<Depth>20.71</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>61</Time>
				<Depth>20.72</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>62</Time>
				<Depth>20.71</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>63</Time>
				<Depth>20.72</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>64</Time>
				<Depth>20.73</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>65</Time>
				<Depth>20.74</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>66</Time>
				<Depth>20.73</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>67</Time>
				<Depth>20.73</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>68</Time>
				<Depth>20.73</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>69</Time>
				<Depth>20.74</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>70</Time>
				<Depth>20.73</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>71</Time>
				<Depth>20.74</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>72</Time>
				<Depth>20.73</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>73</Time>
				<Depth>20.75</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>74</Time>
				<Depth>20.73</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>75</Time>
				<Depth>20.74</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>76</Time>
				<Depth>20.73</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>77</Time>
				<Depth>20.72</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>78</Time>
				<Depth>20.73</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>79</Time>
				<Depth>20.74</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>80</Time>
				<Depth>20.73</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>81</Time>
				<Depth>20.73</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>82</Time>
				<Depth>20.73</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>83</Time>
				<Depth>20.74</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>84</Time>
				<Depth>20.74</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>85</Time>
				<Depth>20.73</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>86</Time>
				<Depth>20.73</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>87</Time>
				<Depth>20.73</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>88</Time>
				<Depth>20.73</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>89</Time>
				<Depth>20.73</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>90</Time>
				<Depth>20.74</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>91</Time>
				<Depth>20.73</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>92</Time>
				<Depth>20.73</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>93</Time>
				<Depth>20.73</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>94</Time>
				<Depth>20.73</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>95</Time>
				<Depth>20.73</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>96</Time>
				<Depth>20.74</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>97</Time>
				<Depth>20.74</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>98</Time>
				<Depth>20.74</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>99</Time>
				<Depth>20.73</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>100</Time>
				<Depth>20.74</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>101</Time>
				<Depth>20.74</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>102</Time>
				<Depth>20.79</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>103</Time>
				<Depth>20.82</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>104</Time>
				<Depth>20.65</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>105</Time>
				<Depth>20.25</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>106</Time>
				<Depth>19.71</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>107</Time>
				<Depth>19.42</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>108</Time>
				<Depth>19.54</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>109</Time>
				<Depth>19.53</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>110</Time>
				<Depth>19.04</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>111</Time>
				<Depth>18.61</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>112</Time>
				<Depth>17.87</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>113</Time>
				<Depth>16.62</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>114</Time>
				<Depth>16.1</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>115</Time>
				<Depth>16.01</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>116</Time>
				<Depth>15.83</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>117</Time>
				<Depth>15.33</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>118</Time>
				<Depth>14.86</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>119</Time>
				<Depth>13.66</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>120</Time>
				<Depth>12.69</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>121</Time>
				<Depth>12.13</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>122</Time>
				<Depth>12.01</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>123</Time>
				<Depth>11.76</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>124</Time>
				<Depth>11.23</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>125</Time>
				<Depth>10.52</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>126</Time>
				<Depth>9.59</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>127</Time>
				<Depth>8.58</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>128</Time>
				<Depth>7.8</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>129</Time>
				<Depth>7.72</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>130</Time>
				<Depth>7.4</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>131</Time>
				<Depth>6.61</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>132</Time>
				<Depth>5.94</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>133</Time>
				<Depth>4.97</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>134</Time>
				<Depth>3.69</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>135</Time>
				<Depth>3.07</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>136</Time>
				<Depth>2.57</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>137</Time>
				<Depth>1.94</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>138</Time>
				<Depth>1.46</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>139</Time>
				<Depth>1.08</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>140</Time>
				<Depth>0.73</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>141</Time>
				<Depth>0.53</Depth>
				<Temperature>301.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>142</Time>
				<Depth>0.18</Depth>
				<Temperature>301.15</Temperature>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
