<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-06-18T14:11:25</DateTime>
			<Duration>18</Duration>
			<Depth>
				<Max>5.11</Max>
				<Avg>3.44</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>60</SurfaceTime>
				<NumberInSeries>3</NumberInSeries>
				<SurfacePressure>101800</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.93</Depth>
				<Temperature>289.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.93</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>2.81</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>3.34</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>3.88</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>4.35</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>4.83</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>5.11</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>5.04</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>5.02</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>4.9</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>4.75</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>4.5</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>3.84</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>3.09</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>2.28</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>1.34</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>0.64</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>0.42</Depth>
				<Temperature>289.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
