<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>3</Battery>
			<DateTime>2016-05-24T12:23:36</DateTime>
			<Duration>46</Duration>
			<Depth>
				<Max>16.32</Max>
				<Avg>8.539999999999999</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>240</SurfaceTime>
				<NumberInSeries>10</NumberInSeries>
				<SurfacePressure>101000</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.25</Depth>
				<Temperature>303.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.25</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>2.24</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>3.13</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>3.92</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>4.68</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>5.43</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>6.23</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>7.07</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>7.93</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>8.82</Depth>
				<Temperature>303.15</Temperature>
				<Events>
					<Notify>
						<Type>Depth</Type>
					</Notify>
				</Events>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>9.68</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>10.58</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>11.44</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>12.33</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>13.21</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>14.09</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>14.95</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>15.7</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>16.14</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>16.32</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>16.25</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>15.8</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>15.19</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>14.43</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>13.7</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>12.96</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>12.02</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>11.05</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>10.11</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>9.300000000000001</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>8.6</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>8.02</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>7.51</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>7.08</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>6.69</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>6.32</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>5.98</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>5.34</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>39</Time>
				<Depth>4.62</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>4.22</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>41</Time>
				<Depth>3.85</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>42</Time>
				<Depth>3.26</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>43</Time>
				<Depth>2.6</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>44</Time>
				<Depth>1.79</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>45</Time>
				<Depth>0.96</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>46</Time>
				<Depth>0.48</Depth>
				<Temperature>301.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
