<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-06-18T15:02:42</DateTime>
			<Duration>48</Duration>
			<Depth>
				<Max>15.91</Max>
				<Avg>9.08</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>120</SurfaceTime>
				<NumberInSeries>12</NumberInSeries>
				<SurfacePressure>101800</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.34</Depth>
				<Temperature>289.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.34</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>2.61</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>3.19</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>4.02</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>4.7</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>5.34</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>6.25</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>6.98</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>7.71</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>8.57</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>9.26</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>9.94</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>10.86</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>11.63</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>12.36</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>13.33</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>14.02</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>14.73</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>15.38</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>15.63</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>15.91</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>15.89</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>15.91</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>15.78</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>15.5</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>15.13</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>14.58</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>13.72</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>13.07</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>12.46</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>11.73</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>11.18</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>10.64</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>9.83</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>9.17</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>8.5</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>7.7</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>7.21</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>39</Time>
				<Depth>6.69</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>6.17</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>41</Time>
				<Depth>5.32</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>42</Time>
				<Depth>4.55</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>43</Time>
				<Depth>3.79</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>44</Time>
				<Depth>2.82</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>45</Time>
				<Depth>2.22</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>46</Time>
				<Depth>1.67</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>47</Time>
				<Depth>0.95</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>48</Time>
				<Depth>0.37</Depth>
				<Temperature>287.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
