<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>3</Battery>
			<DateTime>2016-05-24T11:27:01</DateTime>
			<Duration>98</Duration>
			<Depth>
				<Max>22.85</Max>
				<Avg>15.51</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>300</SurfaceTime>
				<NumberInSeries>3</NumberInSeries>
				<SurfacePressure>101000</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.56</Depth>
				<Temperature>303.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.56</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>2.51</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>3.39</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>4.26</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>5.11</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>6.01</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>6.84</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>7.69</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>8.550000000000001</Depth>
				<Temperature>303.15</Temperature>
				<Events>
					<Notify>
						<Type>Depth</Type>
					</Notify>
				</Events>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>9.43</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>10.37</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>11.22</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>12</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>12.8</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>13.61</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>14.42</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>15.19</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>15.93</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>16.66</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>17.35</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>18.05</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>18.77</Depth>
				<Temperature>300.15</Temperature>
				<Events>
					<Notify>
						<Type>Depth</Type>
					</Notify>
				</Events>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>19.47</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>20.24</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>20.96</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>21.7</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>22.19</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>22.46</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>22.65</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>22.85</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>22.85</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>22.77</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>22.65</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>22.49</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>22.29</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>22.07</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>21.86</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>21.66</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>39</Time>
				<Depth>21.48</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>21.41</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>41</Time>
				<Depth>21.26</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>42</Time>
				<Depth>21.23</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>43</Time>
				<Depth>21.14</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>44</Time>
				<Depth>20.94</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>45</Time>
				<Depth>20.82</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>46</Time>
				<Depth>20.73</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>47</Time>
				<Depth>20.72</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>48</Time>
				<Depth>20.76</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>49</Time>
				<Depth>20.82</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>50</Time>
				<Depth>20.88</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>51</Time>
				<Depth>20.91</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>52</Time>
				<Depth>20.9</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>53</Time>
				<Depth>20.9</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>54</Time>
				<Depth>20.92</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>55</Time>
				<Depth>20.95</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>56</Time>
				<Depth>20.93</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>57</Time>
				<Depth>20.89</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>58</Time>
				<Depth>20.83</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>59</Time>
				<Depth>20.85</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>60</Time>
				<Depth>20.99</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>61</Time>
				<Depth>21.19</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>62</Time>
				<Depth>21.33</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>63</Time>
				<Depth>21.37</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>64</Time>
				<Depth>21.25</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>65</Time>
				<Depth>21.14</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>66</Time>
				<Depth>21.02</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>67</Time>
				<Depth>20.68</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>68</Time>
				<Depth>20.22</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>69</Time>
				<Depth>19.72</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>70</Time>
				<Depth>19.18</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>71</Time>
				<Depth>18.63</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>72</Time>
				<Depth>18.07</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>73</Time>
				<Depth>17.51</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>74</Time>
				<Depth>16.89</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>75</Time>
				<Depth>16.29</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>76</Time>
				<Depth>15.65</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>77</Time>
				<Depth>14.86</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>78</Time>
				<Depth>13.96</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>79</Time>
				<Depth>13.35</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>80</Time>
				<Depth>12.91</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>81</Time>
				<Depth>12.31</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>82</Time>
				<Depth>11.67</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>83</Time>
				<Depth>10.79</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>84</Time>
				<Depth>9.810000000000001</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>85</Time>
				<Depth>9.279999999999999</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>86</Time>
				<Depth>8.73</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>87</Time>
				<Depth>8.109999999999999</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>88</Time>
				<Depth>7.44</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>89</Time>
				<Depth>6.73</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>90</Time>
				<Depth>5.97</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>91</Time>
				<Depth>5.22</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>92</Time>
				<Depth>4.5</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>93</Time>
				<Depth>3.74</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>94</Time>
				<Depth>2.94</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>95</Time>
				<Depth>2.05</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>96</Time>
				<Depth>1.19</Depth>
				<Temperature>300.15</Temperature>
			</Sample>
			<Sample>
				<Time>97</Time>
				<Depth>0.61</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>98</Time>
				<Depth>0.33</Depth>
				<Temperature>301.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
