<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-05-26T11:12:18</DateTime>
			<Duration>51</Duration>
			<Depth>
				<Max>17.95</Max>
				<Avg>9.32</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>0</SurfaceTime>
				<NumberInSeries>1</NumberInSeries>
				<SurfacePressure>101100</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.22</Depth>
				<Temperature>299.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.22</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>2.34</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>3.29</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>4.22</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>5.03</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>5.93</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>6.84</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>7.75</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>8.67</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>9.58</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>10.41</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>11.37</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>12.31</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>13.22</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>14.09</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>15.08</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>16.1</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>16.93</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>17.45</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>17.74</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>17.95</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>17.77</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>17.38</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>16.87</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>16.28</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>15.67</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>15.01</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>14.32</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>13.59</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>12.88</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>12.14</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>11.35</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>10.6</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>9.960000000000001</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>9.33</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>8.619999999999999</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>7.94</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>7.27</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>39</Time>
				<Depth>6.63</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>6.02</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>41</Time>
				<Depth>5.39</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>42</Time>
				<Depth>4.7</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>43</Time>
				<Depth>4.12</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>44</Time>
				<Depth>3.53</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>45</Time>
				<Depth>2.94</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>46</Time>
				<Depth>2.36</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>47</Time>
				<Depth>1.81</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>48</Time>
				<Depth>1.29</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>49</Time>
				<Depth>0.92</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>50</Time>
				<Depth>0.6800000000000001</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>51</Time>
				<Depth>0.43</Depth>
				<Temperature>299.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
