<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-05-14T12:37:41</DateTime>
			<Duration>51</Duration>
			<Depth>
				<Max>14.41</Max>
				<Avg>9.34</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>60</SurfaceTime>
				<NumberInSeries>20</NumberInSeries>
				<SurfacePressure>101300</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.55</Depth>
				<Temperature>302.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.55</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>2.86</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>3.88</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>4.58</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>5.23</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>6.22</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>6.94</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>7.72</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>8.779999999999999</Depth>
				<Temperature>301.15</Temperature>
				<Events>
					<Notify>
						<Type>Depth</Type>
					</Notify>
				</Events>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>9.619999999999999</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>10.54</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>11.47</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>12.55</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>13.11</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>13.4</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>13.59</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>13.77</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>13.92</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>14.03</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>14.06</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>14.13</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>14.19</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>14.41</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>14.39</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>14.23</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>14.16</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>14.12</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>14.13</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>13.89</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>13.61</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>12.98</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>12.54</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>12.05</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>11.5</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>11.17</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>10.54</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>9.75</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>9.289999999999999</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>39</Time>
				<Depth>8.6</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>7.92</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>41</Time>
				<Depth>7.36</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>42</Time>
				<Depth>6.63</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>43</Time>
				<Depth>5.84</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>44</Time>
				<Depth>5.57</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>45</Time>
				<Depth>4.82</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>46</Time>
				<Depth>3.75</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>47</Time>
				<Depth>2.93</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>48</Time>
				<Depth>2.12</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>49</Time>
				<Depth>1.27</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>50</Time>
				<Depth>0.64</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>51</Time>
				<Depth>0.19</Depth>
				<Temperature>301.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
