<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-05-26T11:43:44</DateTime>
			<Duration>79</Duration>
			<Depth>
				<Max>15.22</Max>
				<Avg>10.26</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>420</SurfaceTime>
				<NumberInSeries>6</NumberInSeries>
				<SurfacePressure>101100</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.31</Depth>
				<Temperature>299.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.31</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>2.22</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>2.81</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>3.27</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>3.66</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>4.05</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>4.5</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>5.12</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>5.79</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>6.46</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>7.03</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>7.62</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>8.25</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>8.880000000000001</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>9.460000000000001</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>10.11</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>10.81</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>11.28</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>11.84</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>12.46</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>13.06</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>13.47</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>13.83</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>14.14</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>14.36</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>14.51</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>14.71</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>14.83</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>14.92</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>15.03</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>15.1</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>15.08</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>15.1</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>15.11</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>15.13</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>15.15</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>15.13</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>15.12</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>39</Time>
				<Depth>15.17</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>15.21</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>41</Time>
				<Depth>15.22</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>42</Time>
				<Depth>15.16</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>43</Time>
				<Depth>15.02</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>44</Time>
				<Depth>14.77</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>45</Time>
				<Depth>14.55</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>46</Time>
				<Depth>14.37</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>47</Time>
				<Depth>14.2</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>48</Time>
				<Depth>14.17</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>49</Time>
				<Depth>14.1</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>50</Time>
				<Depth>13.86</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>51</Time>
				<Depth>13.58</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>52</Time>
				<Depth>13.2</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>53</Time>
				<Depth>12.91</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>54</Time>
				<Depth>12.67</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>55</Time>
				<Depth>12.46</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>56</Time>
				<Depth>12.19</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>57</Time>
				<Depth>12.01</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>58</Time>
				<Depth>11.82</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>59</Time>
				<Depth>11.61</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>60</Time>
				<Depth>11.41</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>61</Time>
				<Depth>11.22</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>62</Time>
				<Depth>11.05</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>63</Time>
				<Depth>10.63</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>64</Time>
				<Depth>10.04</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>65</Time>
				<Depth>9.35</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>66</Time>
				<Depth>8.609999999999999</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>67</Time>
				<Depth>8.01</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>68</Time>
				<Depth>7.42</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>69</Time>
				<Depth>6.71</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>70</Time>
				<Depth>5.93</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>71</Time>
				<Depth>5.13</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>72</Time>
				<Depth>4.4</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>73</Time>
				<Depth>3.59</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>74</Time>
				<Depth>2.87</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>75</Time>
				<Depth>2.24</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>76</Time>
				<Depth>1.63</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>77</Time>
				<Depth>1.08</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>78</Time>
				<Depth>0.63</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>79</Time>
				<Depth>0.4</Depth>
				<Temperature>299.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
