<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-05-14T12:58:53</DateTime>
			<Duration>50</Duration>
			<Depth>
				<Max>15.17</Max>
				<Avg>9.390000000000001</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>180</SurfaceTime>
				<NumberInSeries>24</NumberInSeries>
				<SurfacePressure>101300</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.28</Depth>
				<Temperature>302.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.28</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>2.5</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>3.09</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>3.67</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>4.5</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>5.17</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>5.9</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>6.8</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>7.48</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>8.16</Depth>
				<Temperature>302.15</Temperature>
				<Events>
					<Notify>
						<Type>Depth</Type>
					</Notify>
				</Events>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>9.109999999999999</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>9.949999999999999</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>10.78</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>11.62</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>12.4</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>12.79</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>13.29</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>13.87</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>14.23</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>14.51</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>14.86</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>15.11</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>15.17</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>14.99</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>14.75</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>14.63</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>14.45</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>14.29</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>14.11</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>13.81</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>13.69</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>13.26</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>12.71</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>12.42</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>12.49</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>11.64</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>10.89</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>10.15</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>39</Time>
				<Depth>9.220000000000001</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>8.4</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>41</Time>
				<Depth>7.62</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>42</Time>
				<Depth>6.59</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>43</Time>
				<Depth>5.86</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>44</Time>
				<Depth>5.18</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>45</Time>
				<Depth>4.09</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>46</Time>
				<Depth>3.25</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>47</Time>
				<Depth>2.49</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>48</Time>
				<Depth>1.42</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>49</Time>
				<Depth>0.62</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>50</Time>
				<Depth>0.35</Depth>
				<Temperature>301.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
