<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-08-20T14:34:12</DateTime>
			<Duration>60</Duration>
			<Depth>
				<Max>19.05</Max>
				<Avg>11.31</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>180</SurfaceTime>
				<NumberInSeries>9</NumberInSeries>
				<SurfacePressure>101000</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.6</Depth>
				<Temperature>293.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.6</Depth>
				<Temperature>293.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>2.63</Depth>
				<Temperature>293.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>3.1</Depth>
				<Temperature>293.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>3.62</Depth>
				<Temperature>293.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>4.34</Depth>
				<Temperature>293.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>4.94</Depth>
				<Temperature>293.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>5.68</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>6.75</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>7.55</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>8.32</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>9.4</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>10.27</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>11.16</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>12.33</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>13.2</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>14.13</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>15.35</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>16.04</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>16.65</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>17.48</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>18.11</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>18.55</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>18.78</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>18.95</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>19.05</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>18.89</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>18.64</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>18.32</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>18.13</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>18.39</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>17.57</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>17.59</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>17.07</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>16.26</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>16.4</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>15.78</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>15.26</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>14.93</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>39</Time>
				<Depth>14.28</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>14.01</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>41</Time>
				<Depth>13.38</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>42</Time>
				<Depth>12.84</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>43</Time>
				<Depth>12.25</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>44</Time>
				<Depth>12.02</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>45</Time>
				<Depth>11.1</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>46</Time>
				<Depth>11.14</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>47</Time>
				<Depth>10.23</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>48</Time>
				<Depth>9.49</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>49</Time>
				<Depth>9.4</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>50</Time>
				<Depth>8.01</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>51</Time>
				<Depth>7.92</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>52</Time>
				<Depth>7.17</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>53</Time>
				<Depth>5.95</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>54</Time>
				<Depth>5.02</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>55</Time>
				<Depth>4.21</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>56</Time>
				<Depth>3.2</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>57</Time>
				<Depth>2.57</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>58</Time>
				<Depth>1.82</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>59</Time>
				<Depth>0.9</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>60</Time>
				<Depth>0.5</Depth>
				<Temperature>289.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
