<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>3</Battery>
			<DateTime>2016-01-25T13:22:45</DateTime>
			<Duration>40</Duration>
			<Depth>
				<Max>10.47</Max>
				<Avg>6.51</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>480</SurfaceTime>
				<NumberInSeries>7</NumberInSeries>
				<SurfacePressure>100500</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.48</Depth>
				<Temperature>303.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.48</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>2.98</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>3.57</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>4.16</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>4.72</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>5.2</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>5.67</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>6.34</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>7.07</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>7.38</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>8.109999999999999</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>8.710000000000001</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>9.32</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>10.03</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>10.44</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>10.42</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>10.47</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>10.35</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>9.890000000000001</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>9.960000000000001</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>10.19</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>9.789999999999999</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>8.949999999999999</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>8.9</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>8.93</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>8.359999999999999</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>7.74</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>7.02</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>7.04</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>6.57</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>6.02</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>5.31</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>4.78</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>4.24</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>3.45</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>2.85</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>2.22</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>1.35</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>39</Time>
				<Depth>0.62</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>0.12</Depth>
				<Temperature>303.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
