<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-08-21T11:15:55</DateTime>
			<Duration>82</Duration>
			<Depth>
				<Max>29.64</Max>
				<Avg>17.36</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>480</SurfaceTime>
				<NumberInSeries>16</NumberInSeries>
				<SurfacePressure>101500</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.34</Depth>
				<Temperature>291.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.34</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>2.57</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>3.26</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>4.16</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>4.87</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>5.61</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>6.73</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>7.57</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>8.42</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>9.539999999999999</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>10.43</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>11.3</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>12.55</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>13.49</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>14.48</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>15.81</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>16.79</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>17.81</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>19.16</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>20.13</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>20.99</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>22.18</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>23.1</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>23.93</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>25.02</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>25.78</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>26.46</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>27.51</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>28.22</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>28.71</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>29.05</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>29.27</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>29.49</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>29.64</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>29.64</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>29.48</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>29.47</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>29.54</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>39</Time>
				<Depth>29.56</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>29.29</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>41</Time>
				<Depth>29.01</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>42</Time>
				<Depth>28.68</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>43</Time>
				<Depth>28.27</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>44</Time>
				<Depth>27.93</Depth>
				<Temperature>283.15</Temperature>
			</Sample>
			<Sample>
				<Time>45</Time>
				<Depth>27.52</Depth>
				<Temperature>283.15</Temperature>
			</Sample>
			<Sample>
				<Time>46</Time>
				<Depth>26.9</Depth>
				<Temperature>283.15</Temperature>
			</Sample>
			<Sample>
				<Time>47</Time>
				<Depth>26.36</Depth>
				<Temperature>283.15</Temperature>
			</Sample>
			<Sample>
				<Time>48</Time>
				<Depth>25.81</Depth>
				<Temperature>283.15</Temperature>
			</Sample>
			<Sample>
				<Time>49</Time>
				<Depth>25.09</Depth>
				<Temperature>283.15</Temperature>
			</Sample>
			<Sample>
				<Time>50</Time>
				<Depth>24.45</Depth>
				<Temperature>283.15</Temperature>
			</Sample>
			<Sample>
				<Time>51</Time>
				<Depth>23.82</Depth>
				<Temperature>283.15</Temperature>
			</Sample>
			<Sample>
				<Time>52</Time>
				<Depth>22.97</Depth>
				<Temperature>283.15</Temperature>
			</Sample>
			<Sample>
				<Time>53</Time>
				<Depth>22.34</Depth>
				<Temperature>283.15</Temperature>
			</Sample>
			<Sample>
				<Time>54</Time>
				<Depth>21.75</Depth>
				<Temperature>283.15</Temperature>
			</Sample>
			<Sample>
				<Time>55</Time>
				<Depth>20.96</Depth>
				<Temperature>283.15</Temperature>
			</Sample>
			<Sample>
				<Time>56</Time>
				<Depth>20.08</Depth>
				<Temperature>283.15</Temperature>
			</Sample>
			<Sample>
				<Time>57</Time>
				<Depth>19.48</Depth>
				<Temperature>283.15</Temperature>
			</Sample>
			<Sample>
				<Time>58</Time>
				<Depth>19.01</Depth>
				<Temperature>283.15</Temperature>
			</Sample>
			<Sample>
				<Time>59</Time>
				<Depth>18.51</Depth>
				<Temperature>283.15</Temperature>
			</Sample>
			<Sample>
				<Time>60</Time>
				<Depth>17.93</Depth>
				<Temperature>283.15</Temperature>
			</Sample>
			<Sample>
				<Time>61</Time>
				<Depth>17.07</Depth>
				<Temperature>283.15</Temperature>
			</Sample>
			<Sample>
				<Time>62</Time>
				<Depth>16.41</Depth>
				<Temperature>283.15</Temperature>
			</Sample>
			<Sample>
				<Time>63</Time>
				<Depth>15.77</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>64</Time>
				<Depth>14.91</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>65</Time>
				<Depth>14.22</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>66</Time>
				<Depth>13.51</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>67</Time>
				<Depth>12.56</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>68</Time>
				<Depth>11.81</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>69</Time>
				<Depth>11.11</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>70</Time>
				<Depth>10.18</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>71</Time>
				<Depth>9.4</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>72</Time>
				<Depth>8.720000000000001</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>73</Time>
				<Depth>8.02</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>74</Time>
				<Depth>6.95</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>75</Time>
				<Depth>6.12</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>76</Time>
				<Depth>5.25</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>77</Time>
				<Depth>4.22</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>78</Time>
				<Depth>3.43</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>79</Time>
				<Depth>2.66</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>80</Time>
				<Depth>1.52</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>81</Time>
				<Depth>0.51</Depth>
				<Temperature>287.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>82</Time>
				<Depth>0.06</Depth>
				<Temperature>287.15</Temperature>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
