<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-06-19T11:03:26</DateTime>
			<Duration>67</Duration>
			<Depth>
				<Max>22.64</Max>
				<Avg>13.37</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>3420</SurfaceTime>
				<NumberInSeries>11</NumberInSeries>
				<SurfacePressure>102900</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.45</Depth>
				<Temperature>288.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.45</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>2.53</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>3.26</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>4.12</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>4.74</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>5.42</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>6.32</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>6.96</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>7.59</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>8.4</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>9.109999999999999</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>9.82</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>10.75</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>11.43</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>12.16</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>13.14</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>13.88</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>14.71</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>15.8</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>16.66</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>17.55</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>18.79</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>19.62</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>20.3</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>21.34</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>21.91</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>22.19</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>22.3</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>22.35</Depth>
				<Temperature>283.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>22.5</Depth>
				<Temperature>283.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>22.6</Depth>
				<Temperature>283.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>22.64</Depth>
				<Temperature>283.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>22.49</Depth>
				<Temperature>283.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>22.05</Depth>
				<Temperature>283.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>21.88</Depth>
				<Temperature>282.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>22.01</Depth>
				<Temperature>282.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>21.88</Depth>
				<Temperature>282.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>21.92</Depth>
				<Temperature>282.15</Temperature>
			</Sample>
			<Sample>
				<Time>39</Time>
				<Depth>21.62</Depth>
				<Temperature>282.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>20.89</Depth>
				<Temperature>282.15</Temperature>
			</Sample>
			<Sample>
				<Time>41</Time>
				<Depth>20.3</Depth>
				<Temperature>282.15</Temperature>
			</Sample>
			<Sample>
				<Time>42</Time>
				<Depth>19.77</Depth>
				<Temperature>282.15</Temperature>
			</Sample>
			<Sample>
				<Time>43</Time>
				<Depth>18.99</Depth>
				<Temperature>282.15</Temperature>
			</Sample>
			<Sample>
				<Time>44</Time>
				<Depth>18.25</Depth>
				<Temperature>282.15</Temperature>
			</Sample>
			<Sample>
				<Time>45</Time>
				<Depth>17.6</Depth>
				<Temperature>282.15</Temperature>
			</Sample>
			<Sample>
				<Time>46</Time>
				<Depth>16.7</Depth>
				<Temperature>282.15</Temperature>
			</Sample>
			<Sample>
				<Time>47</Time>
				<Depth>16.27</Depth>
				<Temperature>282.15</Temperature>
			</Sample>
			<Sample>
				<Time>48</Time>
				<Depth>15.74</Depth>
				<Temperature>282.15</Temperature>
			</Sample>
			<Sample>
				<Time>49</Time>
				<Depth>14.86</Depth>
				<Temperature>282.15</Temperature>
			</Sample>
			<Sample>
				<Time>50</Time>
				<Depth>14.33</Depth>
				<Temperature>282.15</Temperature>
			</Sample>
			<Sample>
				<Time>51</Time>
				<Depth>13.67</Depth>
				<Temperature>282.15</Temperature>
			</Sample>
			<Sample>
				<Time>52</Time>
				<Depth>12.74</Depth>
				<Temperature>282.15</Temperature>
			</Sample>
			<Sample>
				<Time>53</Time>
				<Depth>11.94</Depth>
				<Temperature>282.15</Temperature>
			</Sample>
			<Sample>
				<Time>54</Time>
				<Depth>11.17</Depth>
				<Temperature>282.15</Temperature>
			</Sample>
			<Sample>
				<Time>55</Time>
				<Depth>9.83</Depth>
				<Temperature>282.15</Temperature>
			</Sample>
			<Sample>
				<Time>56</Time>
				<Depth>8.880000000000001</Depth>
				<Temperature>282.15</Temperature>
			</Sample>
			<Sample>
				<Time>57</Time>
				<Depth>8.43</Depth>
				<Temperature>282.15</Temperature>
			</Sample>
			<Sample>
				<Time>58</Time>
				<Depth>7.61</Depth>
				<Temperature>283.15</Temperature>
			</Sample>
			<Sample>
				<Time>59</Time>
				<Depth>6.89</Depth>
				<Temperature>283.15</Temperature>
			</Sample>
			<Sample>
				<Time>60</Time>
				<Depth>6.09</Depth>
				<Temperature>283.15</Temperature>
			</Sample>
			<Sample>
				<Time>61</Time>
				<Depth>5.03</Depth>
				<Temperature>283.15</Temperature>
			</Sample>
			<Sample>
				<Time>62</Time>
				<Depth>4.24</Depth>
				<Temperature>283.15</Temperature>
			</Sample>
			<Sample>
				<Time>63</Time>
				<Depth>3.53</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>64</Time>
				<Depth>2.85</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>65</Time>
				<Depth>1.87</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>66</Time>
				<Depth>1.08</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>67</Time>
				<Depth>0.45</Depth>
				<Temperature>285.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
