<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-07-17T09:24:56</DateTime>
			<Duration>2500</Duration>
			<Depth>
				<Max>34.17</Max>
				<Avg>15.9</Avg>
			</Depth>
			<Diving>
				<DiveMode>EAN</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>0</SurfaceTime>
				<NumberInSeries>1</NumberInSeries>
				<SurfacePressure>101800</SurfacePressure>
				<Algorithm>Suunto Technical RGBM</Algorithm>
				<Gases>
					<Gas>
						<State>Primary</State>
						<Oxygen>0.21</Oxygen>
						<Helium>0</Helium>
						<PO2>140000</PO2>
						<UsedPressure>0</UsedPressure>
					</Gas>
					<Gas>
						<State>Primary</State>
						<Oxygen>0.32</Oxygen>
						<Helium>0</Helium>
						<PO2>140000</PO2>
					</Gas>
					<Gas>
						<State>Primary</State>
						<Oxygen>0.36</Oxygen>
						<Helium>0</Helium>
						<PO2>140000</PO2>
					</Gas>
				</Gases>
				<StartTissue>
					<CNS>0.008750000000000001</CNS>
					<OTU>1.6875</OTU>
					<Nitrogen>
						<Pressure>79000</Pressure>
						<Pressure>79000</Pressure>
						<Pressure>79000</Pressure>
						<Pressure>79000</Pressure>
						<Pressure>79000</Pressure>
						<Pressure>79000</Pressure>
						<Pressure>79000</Pressure>
						<Pressure>79000</Pressure>
						<Pressure>79000</Pressure>
					</Nitrogen>
					<RgbmNitrogen>1</RgbmNitrogen>
				</StartTissue>
				<EndTissue>
					<CNS>0.05515625</CNS>
					<OTU>14.66015625</OTU>
					<OLF>0.05515625</OLF>
					<Nitrogen>
						<Pressure>141100</Pressure>
						<Pressure>162700</Pressure>
						<Pressure>174400</Pressure>
						<Pressure>162900</Pressure>
						<Pressure>138500</Pressure>
						<Pressure>115500</Pressure>
						<Pressure>105100</Pressure>
						<Pressure>93000</Pressure>
						<Pressure>86300</Pressure>
					</Nitrogen>
					<RgbmNitrogen>1</RgbmNitrogen>
				</EndTissue>
			</Diving>
			<SampleInterval>20</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<GasSwitch>
						<GasNumber>1</GasNumber>
					</GasSwitch>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.55</Depth>
				<Temperature>302.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>6.2</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>6.91</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>60</Time>
				<Depth>8.359999999999999</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>80</Time>
				<Depth>8.949999999999999</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>100</Time>
				<Depth>8.15</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>120</Time>
				<Depth>8.94</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>140</Time>
				<Depth>9.300000000000001</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>160</Time>
				<Depth>12.05</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>180</Time>
				<Depth>15.78</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>200</Time>
				<Depth>17.79</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>220</Time>
				<Depth>19.72</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>240</Time>
				<Depth>22.9</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>260</Time>
				<Depth>24.26</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>280</Time>
				<Depth>27.88</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>300</Time>
				<Depth>30.31</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>320</Time>
				<Depth>33.53</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>340</Time>
				<Depth>33.67</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>360</Time>
				<Depth>33.31</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>380</Time>
				<Depth>32.91</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>400</Time>
				<Depth>31.98</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>420</Time>
				<Depth>31.84</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>440</Time>
				<Depth>32.25</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>460</Time>
				<Depth>32.49</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>480</Time>
				<Depth>31.75</Depth>
				<Temperature>301.15</Temperature>
				<Events>
					<Notify>
						<Type>Gas Available</Type>
					</Notify>
				</Events>
			</Sample>
			<Sample>
				<Time>493</Time>
			</Sample>
			<Sample>
				<Time>500</Time>
				<Depth>30.19</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>520</Time>
				<Depth>30.04</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>540</Time>
				<Depth>30.23</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>560</Time>
				<Depth>30.66</Depth>
				<Temperature>301.15</Temperature>
				<Events>
					<Notify>
						<Type>Gas Available</Type>
					</Notify>
				</Events>
			</Sample>
			<Sample>
				<Time>570</Time>
			</Sample>
			<Sample>
				<Time>580</Time>
				<Depth>31.23</Depth>
				<Temperature>301.15</Temperature>
				<Events>
					<Notify>
						<Type>Gas Available</Type>
					</Notify>
				</Events>
			</Sample>
			<Sample>
				<Time>590</Time>
			</Sample>
			<Sample>
				<Time>600</Time>
				<Depth>29.7</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>620</Time>
				<Depth>27.51</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>640</Time>
				<Depth>26.76</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>660</Time>
				<Depth>24.61</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>680</Time>
				<Depth>23.6</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>700</Time>
				<Depth>23.77</Depth>
				<Temperature>301.15</Temperature>
				<Events>
					<Alarm>
						<Type>Ascent Speed</Type>
						<Active>true</Active>
					</Alarm>
				</Events>
			</Sample>
			<Sample>
				<Time>713</Time>
				<Events>
					<Warning>
						<Type>Mandatory Safety Stop</Type>
						<Active>true</Active>
					</Warning>
					<Alarm>
						<Type>Ascent Speed</Type>
						<Active>false</Active>
					</Alarm>
				</Events>
			</Sample>
			<Sample>
				<Time>714</Time>
			</Sample>
			<Sample>
				<Time>720</Time>
				<Depth>21.32</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>740</Time>
				<Depth>21.69</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>760</Time>
				<Depth>21.74</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>780</Time>
				<Depth>21.45</Depth>
				<Temperature>301.15</Temperature>
			</Sample>
			<Sample>
				<Time>800</Time>
				<Depth>21.83</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>820</Time>
				<Depth>22.95</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>840</Time>
				<Depth>24.35</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>860</Time>
				<Depth>26.64</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>880</Time>
				<Depth>24.66</Depth>
				<Temperature>302.15</Temperature>
				<Events>
					<Alarm>
						<Type>Ascent Speed</Type>
						<Active>true</Active>
					</Alarm>
				</Events>
			</Sample>
			<Sample>
				<Time>881</Time>
				<Events>
					<Alarm>
						<Type>Ascent Speed</Type>
						<Active>false</Active>
					</Alarm>
				</Events>
			</Sample>
			<Sample>
				<Time>886</Time>
			</Sample>
			<Sample>
				<Time>900</Time>
				<Depth>22.24</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>920</Time>
				<Depth>20.35</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>940</Time>
				<Depth>20.78</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>960</Time>
				<Depth>21.63</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>980</Time>
				<Depth>21.14</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>1000</Time>
				<Depth>20.62</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>1020</Time>
				<Depth>21</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>1040</Time>
				<Depth>18.89</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>1060</Time>
				<Depth>17.64</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>1080</Time>
				<Depth>18.36</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>1100</Time>
				<Depth>19.48</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>1120</Time>
				<Depth>19.44</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>1140</Time>
				<Depth>19.53</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>1160</Time>
				<Depth>20.47</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>1180</Time>
				<Depth>21.62</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>1200</Time>
				<Depth>20.32</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>1220</Time>
				<Depth>20.05</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>1240</Time>
				<Depth>21.11</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>1260</Time>
				<Depth>19.59</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>1280</Time>
				<Depth>19.73</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>1300</Time>
				<Depth>19.12</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>1320</Time>
				<Depth>17</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>1340</Time>
				<Depth>17.19</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>1360</Time>
				<Depth>17.2</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>1380</Time>
				<Depth>16.54</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>1400</Time>
				<Depth>16.53</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>1420</Time>
				<Depth>15.25</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>1440</Time>
				<Depth>12.2</Depth>
				<Temperature>302.15</Temperature>
				<Events>
					<Alarm>
						<Type>Ascent Speed</Type>
						<Active>true</Active>
					</Alarm>
				</Events>
			</Sample>
			<Sample>
				<Time>1443</Time>
				<Events>
					<Alarm>
						<Type>Ascent Speed</Type>
						<Active>false</Active>
					</Alarm>
				</Events>
			</Sample>
			<Sample>
				<Time>1444</Time>
			</Sample>
			<Sample>
				<Time>1460</Time>
				<Depth>10.3</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>1480</Time>
				<Depth>8.539999999999999</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>1500</Time>
				<Depth>9.779999999999999</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>1520</Time>
				<Depth>10.21</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>1540</Time>
				<Depth>10.23</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>1560</Time>
				<Depth>10.27</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>1580</Time>
				<Depth>9.550000000000001</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>1600</Time>
				<Depth>8.810000000000001</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>1620</Time>
				<Depth>8.02</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>1640</Time>
				<Depth>9.34</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>1660</Time>
				<Depth>9.59</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>1680</Time>
				<Depth>8.619999999999999</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>1700</Time>
				<Depth>7.41</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>1720</Time>
				<Depth>9.609999999999999</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>1740</Time>
				<Depth>9.82</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>1760</Time>
				<Depth>9.59</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>1780</Time>
				<Depth>10.06</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>1800</Time>
				<Depth>8.32</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>1820</Time>
				<Depth>8.220000000000001</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>1840</Time>
				<Depth>7.78</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>1860</Time>
				<Depth>7.49</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>1880</Time>
				<Depth>7.73</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>1900</Time>
				<Depth>8.359999999999999</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>1920</Time>
				<Depth>8.869999999999999</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>1940</Time>
				<Depth>9.369999999999999</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>1960</Time>
				<Depth>9.210000000000001</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>1980</Time>
				<Depth>9.33</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>2000</Time>
				<Depth>9.300000000000001</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>2020</Time>
				<Depth>9.49</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>2040</Time>
				<Depth>9.08</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>2060</Time>
				<Depth>8.42</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>2080</Time>
				<Depth>8.779999999999999</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>2100</Time>
				<Depth>8.15</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>2120</Time>
				<Depth>7.38</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>2140</Time>
				<Depth>6.64</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>2160</Time>
				<Depth>8.23</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>2180</Time>
				<Depth>9.01</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>2200</Time>
				<Depth>8.060000000000001</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>2220</Time>
				<Depth>9.140000000000001</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>2240</Time>
				<Depth>9.5</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>2260</Time>
				<Depth>8.949999999999999</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>2280</Time>
				<Depth>7.91</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>2300</Time>
				<Depth>7.41</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>2320</Time>
				<Depth>5.53</Depth>
				<Temperature>302.15</Temperature>
			</Sample>
			<Sample>
				<Time>2340</Time>
				<Depth>5.42</Depth>
				<Temperature>303.15</Temperature>
				<Events>
					<Warning>
						<Type>Mandatory Safety Stop</Type>
						<Active>false</Active>
					</Warning>
				</Events>
			</Sample>
			<Sample>
				<Time>2347</Time>
			</Sample>
			<Sample>
				<Time>2360</Time>
				<Depth>4.53</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>2380</Time>
				<Depth>5.13</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>2400</Time>
				<Depth>4.58</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>2420</Time>
				<Depth>4.03</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>2440</Time>
				<Depth>2.78</Depth>
				<Temperature>303.15</Temperature>
				<Events>
					<Notify>
						<Type>Tissue Level</Type>
					</Notify>
				</Events>
			</Sample>
			<Sample>
				<Time>2452</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>2456</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>2456</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>2460</Time>
				<Depth>0.32</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>2480</Time>
				<Depth>0.19</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>2500</Time>
				<Depth>0.44</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>2520</Time>
				<Depth>0.58</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>2540</Time>
				<Depth>0.46</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>2555</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>2555</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>2560</Time>
				<Depth>0.55</Depth>
				<TankPressure>3910000</TankPressure>
				<Temperature>303.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>2580</Time>
				<Depth>0.5</Depth>
				<TankPressure>3910000</TankPressure>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>2600</Time>
				<Depth>0.5</Depth>
				<TankPressure>3910000</TankPressure>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>2620</Time>
				<Depth>0.48</Depth>
				<TankPressure>3910000</TankPressure>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>2632</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>2632</Time>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>2634</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>2634</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<Warning>
						<Type>Tank Pressure</Type>
						<Active>true</Active>
					</Warning>
				</Events>
			</Sample>
			<Sample>
				<Time>2635</Time>
				<Events>
					<Notify>
						<Type>Tank Pressure</Type>
						<Active>true</Active>
					</Notify>
				</Events>
			</Sample>
			<Sample>
				<Time>2640</Time>
				<Depth>1.65</Depth>
				<TankPressure>3910000</TankPressure>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>2660</Time>
				<Depth>1.29</Depth>
				<TankPressure>3910000</TankPressure>
				<Temperature>303.15</Temperature>
				<Events>
					<Notify>
						<Type>Tissue Level</Type>
					</Notify>
				</Events>
			</Sample>
			<Sample>
				<Time>2662</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>2667</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>2667</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>2680</Time>
				<Depth>1.9</Depth>
				<TankPressure>3910000</TankPressure>
				<Temperature>303.15</Temperature>
				<Events>
					<Notify>
						<Type>Tissue Level</Type>
					</Notify>
				</Events>
			</Sample>
			<Sample>
				<Time>2687</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
