<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-09-06T12:51:30</DateTime>
			<Duration>99</Duration>
			<Depth>
				<Max>20.4</Max>
				<Avg>12.81</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>60</SurfaceTime>
				<NumberInSeries>5</NumberInSeries>
				<SurfacePressure>101000</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.45</Depth>
				<Temperature>297.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.45</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>2.43</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>3.39</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>4.3</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>5.18</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>6.08</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>6.96</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>7.87</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>8.800000000000001</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>9.800000000000001</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>10.73</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>11.62</Depth>
				<Temperature>296.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>12.45</Depth>
				<Temperature>295.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>13.19</Depth>
				<Temperature>295.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>13.9</Depth>
				<Temperature>294.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>14.56</Depth>
				<Temperature>293.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>15.24</Depth>
				<Temperature>293.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>15.92</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>16.6</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>17.3</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>17.93</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>18.49</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>18.99</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>19.45</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>19.87</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>20.09</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>20.21</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>20.29</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>20.33</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>20.36</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>20.38</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>20.37</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>20.39</Depth>
				<Temperature>283.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>20.39</Depth>
				<Temperature>283.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>20.39</Depth>
				<Temperature>283.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>20.38</Depth>
				<Temperature>283.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>20.36</Depth>
				<Temperature>283.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>20.35</Depth>
				<Temperature>283.15</Temperature>
			</Sample>
			<Sample>
				<Time>39</Time>
				<Depth>20.35</Depth>
				<Temperature>282.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>20.38</Depth>
				<Temperature>282.15</Temperature>
			</Sample>
			<Sample>
				<Time>41</Time>
				<Depth>20.39</Depth>
				<Temperature>282.15</Temperature>
			</Sample>
			<Sample>
				<Time>42</Time>
				<Depth>20.38</Depth>
				<Temperature>282.15</Temperature>
			</Sample>
			<Sample>
				<Time>43</Time>
				<Depth>20.37</Depth>
				<Temperature>282.15</Temperature>
			</Sample>
			<Sample>
				<Time>44</Time>
				<Depth>20.37</Depth>
				<Temperature>282.15</Temperature>
			</Sample>
			<Sample>
				<Time>45</Time>
				<Depth>20.4</Depth>
				<Temperature>282.15</Temperature>
			</Sample>
			<Sample>
				<Time>46</Time>
				<Depth>20.38</Depth>
				<Temperature>282.15</Temperature>
			</Sample>
			<Sample>
				<Time>47</Time>
				<Depth>20.4</Depth>
				<Temperature>282.15</Temperature>
			</Sample>
			<Sample>
				<Time>48</Time>
				<Depth>20.34</Depth>
				<Temperature>281.15</Temperature>
			</Sample>
			<Sample>
				<Time>49</Time>
				<Depth>20.24</Depth>
				<Temperature>281.15</Temperature>
			</Sample>
			<Sample>
				<Time>50</Time>
				<Depth>19.95</Depth>
				<Temperature>281.15</Temperature>
			</Sample>
			<Sample>
				<Time>51</Time>
				<Depth>19.53</Depth>
				<Temperature>281.15</Temperature>
			</Sample>
			<Sample>
				<Time>52</Time>
				<Depth>19.04</Depth>
				<Temperature>281.15</Temperature>
			</Sample>
			<Sample>
				<Time>53</Time>
				<Depth>18.48</Depth>
				<Temperature>281.15</Temperature>
			</Sample>
			<Sample>
				<Time>54</Time>
				<Depth>17.87</Depth>
				<Temperature>281.15</Temperature>
			</Sample>
			<Sample>
				<Time>55</Time>
				<Depth>17.24</Depth>
				<Temperature>280.15</Temperature>
			</Sample>
			<Sample>
				<Time>56</Time>
				<Depth>16.6</Depth>
				<Temperature>280.15</Temperature>
			</Sample>
			<Sample>
				<Time>57</Time>
				<Depth>15.94</Depth>
				<Temperature>280.15</Temperature>
			</Sample>
			<Sample>
				<Time>58</Time>
				<Depth>15.28</Depth>
				<Temperature>280.15</Temperature>
			</Sample>
			<Sample>
				<Time>59</Time>
				<Depth>14.57</Depth>
				<Temperature>280.15</Temperature>
			</Sample>
			<Sample>
				<Time>60</Time>
				<Depth>13.91</Depth>
				<Temperature>280.15</Temperature>
			</Sample>
			<Sample>
				<Time>61</Time>
				<Depth>13.24</Depth>
				<Temperature>280.15</Temperature>
			</Sample>
			<Sample>
				<Time>62</Time>
				<Depth>12.53</Depth>
				<Temperature>280.15</Temperature>
			</Sample>
			<Sample>
				<Time>63</Time>
				<Depth>11.86</Depth>
				<Temperature>280.15</Temperature>
			</Sample>
			<Sample>
				<Time>64</Time>
				<Depth>11.16</Depth>
				<Temperature>280.15</Temperature>
			</Sample>
			<Sample>
				<Time>65</Time>
				<Depth>10.53</Depth>
				<Temperature>281.15</Temperature>
			</Sample>
			<Sample>
				<Time>66</Time>
				<Depth>10.01</Depth>
				<Temperature>281.15</Temperature>
			</Sample>
			<Sample>
				<Time>67</Time>
				<Depth>9.59</Depth>
				<Temperature>281.15</Temperature>
			</Sample>
			<Sample>
				<Time>68</Time>
				<Depth>9.26</Depth>
				<Temperature>282.15</Temperature>
			</Sample>
			<Sample>
				<Time>69</Time>
				<Depth>9.060000000000001</Depth>
				<Temperature>282.15</Temperature>
			</Sample>
			<Sample>
				<Time>70</Time>
				<Depth>8.93</Depth>
				<Temperature>282.15</Temperature>
			</Sample>
			<Sample>
				<Time>71</Time>
				<Depth>8.869999999999999</Depth>
				<Temperature>283.15</Temperature>
			</Sample>
			<Sample>
				<Time>72</Time>
				<Depth>8.82</Depth>
				<Temperature>283.15</Temperature>
			</Sample>
			<Sample>
				<Time>73</Time>
				<Depth>8.85</Depth>
				<Temperature>283.15</Temperature>
			</Sample>
			<Sample>
				<Time>74</Time>
				<Depth>8.92</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>75</Time>
				<Depth>9.039999999999999</Depth>
				<Temperature>284.15</Temperature>
			</Sample>
			<Sample>
				<Time>76</Time>
				<Depth>9.07</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>77</Time>
				<Depth>9.050000000000001</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>78</Time>
				<Depth>9.039999999999999</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>79</Time>
				<Depth>9.119999999999999</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>80</Time>
				<Depth>9.16</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>81</Time>
				<Depth>9.08</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>82</Time>
				<Depth>8.84</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>83</Time>
				<Depth>8.539999999999999</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>84</Time>
				<Depth>8.24</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>85</Time>
				<Depth>8.18</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>86</Time>
				<Depth>8.039999999999999</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>87</Time>
				<Depth>7.71</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>88</Time>
				<Depth>7.26</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>89</Time>
				<Depth>6.72</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>90</Time>
				<Depth>6.12</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>91</Time>
				<Depth>5.45</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>92</Time>
				<Depth>4.76</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>93</Time>
				<Depth>4.05</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>94</Time>
				<Depth>3.34</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>95</Time>
				<Depth>2.67</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>96</Time>
				<Depth>1.91</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>97</Time>
				<Depth>1.03</Depth>
				<Temperature>293.15</Temperature>
			</Sample>
			<Sample>
				<Time>98</Time>
				<Depth>0.57</Depth>
				<Temperature>293.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>99</Time>
				<Depth>0.39</Depth>
				<Temperature>293.15</Temperature>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
