<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-05-26T11:24:43</DateTime>
			<Duration>68</Duration>
			<Depth>
				<Max>21.45</Max>
				<Avg>12.7</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>300</SurfaceTime>
				<NumberInSeries>3</NumberInSeries>
				<SurfacePressure>101100</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.32</Depth>
				<Temperature>299.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.32</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>2.32</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>3.28</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>4.2</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>5.12</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>5.99</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>6.77</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>7.61</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>8.48</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>9.390000000000001</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>10.29</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>11.16</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>11.93</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>12.74</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>13.63</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>14.57</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>15.5</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>16.42</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>17.05</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>17.41</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>17.66</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>17.84</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>18.02</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>18.21</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>18.41</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>18.63</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>18.85</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>19.12</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>19.42</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>19.71</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>20.04</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>20.37</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>20.7</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>20.97</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>21.15</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>21.44</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>21.45</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>21.15</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>39</Time>
				<Depth>20.67</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>20.13</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>41</Time>
				<Depth>19.55</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>42</Time>
				<Depth>18.93</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>43</Time>
				<Depth>18.27</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>44</Time>
				<Depth>17.61</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>45</Time>
				<Depth>16.93</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>46</Time>
				<Depth>16.21</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>47</Time>
				<Depth>15.49</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>48</Time>
				<Depth>14.79</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>49</Time>
				<Depth>14.03</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>50</Time>
				<Depth>13.31</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>51</Time>
				<Depth>12.56</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>52</Time>
				<Depth>11.79</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>53</Time>
				<Depth>11.08</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>54</Time>
				<Depth>10.32</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>55</Time>
				<Depth>9.550000000000001</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>56</Time>
				<Depth>8.74</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>57</Time>
				<Depth>7.94</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>58</Time>
				<Depth>7.19</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>59</Time>
				<Depth>6.42</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>60</Time>
				<Depth>5.63</Depth>
				<Temperature>298.15</Temperature>
			</Sample>
			<Sample>
				<Time>61</Time>
				<Depth>4.83</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>62</Time>
				<Depth>4.02</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>63</Time>
				<Depth>3.21</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>64</Time>
				<Depth>2.44</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>65</Time>
				<Depth>1.68</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>66</Time>
				<Depth>1.05</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>67</Time>
				<Depth>0.61</Depth>
				<Temperature>299.15</Temperature>
			</Sample>
			<Sample>
				<Time>68</Time>
				<Depth>0.37</Depth>
				<Temperature>299.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
