<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-08-21T08:59:32</DateTime>
			<Duration>73</Duration>
			<Depth>
				<Max>17.03</Max>
				<Avg>11.74</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>120</SurfaceTime>
				<NumberInSeries>4</NumberInSeries>
				<SurfacePressure>101500</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.4</Depth>
				<Temperature>290.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.4</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>2.74</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>3.79</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>4.52</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>5.26</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>6.32</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>7.18</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>8.02</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>9.15</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>10.04</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>10.86</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>11.95</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>12.75</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>13.59</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>14.7</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>15.59</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>16.41</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>16.89</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>17.03</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>16.85</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>16.34</Depth>
				<Temperature>288.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>16.11</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>16.03</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>15.98</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>15.96</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>15.87</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>15.72</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>15.76</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>15.65</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>15.74</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>15.83</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>15.88</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>15.91</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>15.81</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>15.72</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>15.77</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>15.82</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>15.86</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>39</Time>
				<Depth>15.69</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>15.59</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>41</Time>
				<Depth>15.51</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>42</Time>
				<Depth>15.46</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>43</Time>
				<Depth>15.54</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>44</Time>
				<Depth>15.41</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>45</Time>
				<Depth>15.39</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>46</Time>
				<Depth>15.47</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>47</Time>
				<Depth>15.44</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>48</Time>
				<Depth>15.41</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>49</Time>
				<Depth>15.5</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>50</Time>
				<Depth>15.43</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>51</Time>
				<Depth>15.05</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>52</Time>
				<Depth>14.37</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>53</Time>
				<Depth>13.79</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>54</Time>
				<Depth>13.16</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>55</Time>
				<Depth>12.31</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>56</Time>
				<Depth>11.66</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>57</Time>
				<Depth>10.9</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>58</Time>
				<Depth>10.19</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>59</Time>
				<Depth>9.810000000000001</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>60</Time>
				<Depth>9.25</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>61</Time>
				<Depth>8.59</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>62</Time>
				<Depth>8.289999999999999</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>63</Time>
				<Depth>7.77</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>64</Time>
				<Depth>6.93</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>65</Time>
				<Depth>6.3</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>66</Time>
				<Depth>5.61</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>67</Time>
				<Depth>4.65</Depth>
				<Temperature>285.15</Temperature>
			</Sample>
			<Sample>
				<Time>68</Time>
				<Depth>4.01</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>69</Time>
				<Depth>3.28</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>70</Time>
				<Depth>2.39</Depth>
				<Temperature>286.15</Temperature>
			</Sample>
			<Sample>
				<Time>71</Time>
				<Depth>1.68</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>72</Time>
				<Depth>0.7</Depth>
				<Temperature>287.15</Temperature>
			</Sample>
			<Sample>
				<Time>73</Time>
				<Depth>0.1</Depth>
				<Temperature>287.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
