<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-08-20T15:50:18</DateTime>
			<Duration>38</Duration>
			<Depth>
				<Max>11.74</Max>
				<Avg>7.19</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>180</SurfaceTime>
				<NumberInSeries>18</NumberInSeries>
				<SurfacePressure>101000</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.41</Depth>
				<Temperature>292.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.41</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>2.86</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>3.52</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>4.34</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>5.02</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>5.77</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>6.73</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>7.46</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>8.210000000000001</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>9.220000000000001</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>10.01</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>10.63</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>11.26</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>11.44</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>11.6</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>11.64</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>11.73</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>11.74</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>11.7</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>11.56</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>11.34</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>10.87</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>10.55</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>10.1</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>9.289999999999999</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>8.51</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>8</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>7.12</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>6.44</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>5.74</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>4.61</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>3.78</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>3.13</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>2.3</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>1.56</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>1.16</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>0.59</Depth>
				<Temperature>291.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>0.39</Depth>
				<Temperature>291.15</Temperature>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
