<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-09-10T09:01:43</DateTime>
			<Duration>503</Duration>
			<Depth>
				<Max>4.08</Max>
				<Avg>3.15</Avg>
			</Depth>
			<Diving>
				<DiveMode>Air</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>420</SurfaceTime>
				<NumberInSeries>2</NumberInSeries>
				<SurfacePressure>101500</SurfacePressure>
				<Algorithm>Suunto Technical RGBM</Algorithm>
				<Gases>
					<Gas>
						<State>Air</State>
						<Oxygen>0.210</Oxygen>
					</Gas>
				</Gases>
				<StartTissue>
					<CNS>0</CNS>
					<OTU>0</OTU>
					<Nitrogen>
						<Pressure>111900</Pressure>
						<Pressure>121500</Pressure>
						<Pressure>127200</Pressure>
						<Pressure>124200</Pressure>
						<Pressure>113500</Pressure>
						<Pressure>101100</Pressure>
						<Pressure>95100</Pressure>
						<Pressure>87800</Pressure>
						<Pressure>83600</Pressure>
					</Nitrogen>
					<RgbmNitrogen>0.9148393987945372</RgbmNitrogen>
				</StartTissue>
				<EndTissue>
					<CNS>0</CNS>
					<OTU>0</OTU>
					<OLF>0</OLF>
					<Nitrogen>
						<Pressure>105700</Pressure>
						<Pressure>112800</Pressure>
						<Pressure>120000</Pressure>
						<Pressure>120400</Pressure>
						<Pressure>112400</Pressure>
						<Pressure>101300</Pressure>
						<Pressure>95500</Pressure>
						<Pressure>88200</Pressure>
						<Pressure>83900</Pressure>
					</Nitrogen>
					<RgbmNitrogen>0.9148393987945372</RgbmNitrogen>
				</EndTissue>
			</Diving>
			<SampleInterval>20</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.22</Depth>
				<Temperature>292.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>2.17</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>2.91</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>60</Time>
				<Depth>3.64</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>80</Time>
				<Depth>3.57</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>100</Time>
				<Depth>3.55</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>120</Time>
				<Depth>3.15</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>140</Time>
				<Depth>3.87</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>160</Time>
				<Depth>3.48</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>180</Time>
				<Depth>3.93</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>200</Time>
				<Depth>3.65</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>220</Time>
				<Depth>3.76</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>240</Time>
				<Depth>3.72</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>260</Time>
				<Depth>3.75</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>280</Time>
				<Depth>3.78</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>300</Time>
				<Depth>3.9</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>320</Time>
				<Depth>3.3</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>340</Time>
				<Depth>3.64</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>360</Time>
				<Depth>3.26</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>380</Time>
				<Depth>2.64</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>400</Time>
				<Depth>2.72</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>420</Time>
				<Depth>2.87</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>440</Time>
				<Depth>2.49</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>460</Time>
				<Depth>1.87</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>480</Time>
				<Depth>1.5</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>500</Time>
				<Depth>1.3</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>503</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>503</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
