<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-05-12T14:23:06</DateTime>
			<Duration>51</Duration>
			<Depth>
				<Max>24.67</Max>
				<Avg>13.11</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>600</SurfaceTime>
				<NumberInSeries>31</NumberInSeries>
				<SurfacePressure>101300</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.51</Depth>
				<Temperature>297.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.51</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>3.17</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>4.08</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>4.99</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>6.26</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>7.2</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>8.25</Depth>
				<Temperature>297.15</Temperature>
				<Events>
					<Notify>
						<Type>Depth</Type>
					</Notify>
				</Events>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>9.630000000000001</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>10.74</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>11.76</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>12.75</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>14.04</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>15.02</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>16</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>17.3</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>18.29</Depth>
				<Temperature>297.15</Temperature>
				<Events>
					<Notify>
						<Type>Depth</Type>
					</Notify>
				</Events>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>19.32</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>20.34</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>21.76</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>22.64</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>23.43</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>24.25</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>24.67</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>24.5</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>23.85</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>23.17</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>22.42</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>21.34</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>20.5</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>19.68</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>18.59</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>17.77</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>16.95</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>15.83</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>14.95</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>14.07</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>12.93</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>12.07</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>39</Time>
				<Depth>11.18</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>10.06</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>41</Time>
				<Depth>9.210000000000001</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>42</Time>
				<Depth>8.43</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>43</Time>
				<Depth>7.59</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>44</Time>
				<Depth>6.51</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>45</Time>
				<Depth>5.65</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>46</Time>
				<Depth>4.8</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>47</Time>
				<Depth>3.73</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>48</Time>
				<Depth>2.93</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>49</Time>
				<Depth>2.08</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>50</Time>
				<Depth>0.7</Depth>
				<Temperature>297.15</Temperature>
			</Sample>
			<Sample>
				<Time>51</Time>
				<Depth>0.09</Depth>
				<Temperature>297.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
