<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-08-20T15:35:22</DateTime>
			<Duration>44</Duration>
			<Depth>
				<Max>11.54</Max>
				<Avg>6.44</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>540</SurfaceTime>
				<NumberInSeries>15</NumberInSeries>
				<SurfacePressure>101000</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.57</Depth>
				<Temperature>292.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.57</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>2.69</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>3.09</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>3.55</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>3.82</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>4.05</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>4.38</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>4.64</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>4.98</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>5.57</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>6.08</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>6.65</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>7.5</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>8.16</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>8.84</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>9.74</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>10.26</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>10.68</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>11.17</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>11.47</Depth>
				<Temperature>292.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>11.54</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>11.37</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>10.96</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>10.81</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>10.24</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>9.76</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>9.4</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>28</Time>
				<Depth>8.74</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>29</Time>
				<Depth>8.32</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>30</Time>
				<Depth>8.08</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>31</Time>
				<Depth>7.44</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>32</Time>
				<Depth>6.81</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>33</Time>
				<Depth>6.34</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>34</Time>
				<Depth>5.92</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>35</Time>
				<Depth>5.26</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>36</Time>
				<Depth>4.69</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>37</Time>
				<Depth>4.07</Depth>
				<Temperature>290.15</Temperature>
			</Sample>
			<Sample>
				<Time>38</Time>
				<Depth>3.7</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>39</Time>
				<Depth>3.33</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>40</Time>
				<Depth>2.8</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>41</Time>
				<Depth>2.23</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>42</Time>
				<Depth>1.68</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>43</Time>
				<Depth>0.8</Depth>
				<Temperature>291.15</Temperature>
			</Sample>
			<Sample>
				<Time>44</Time>
				<Depth>0.33</Depth>
				<Temperature>291.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
