<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>2.9</Battery>
			<DateTime>2016-06-18T14:08:03</DateTime>
			<Duration>27</Duration>
			<Depth>
				<Max>5.08</Max>
				<Avg>3.69</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>0</SurfaceTime>
				<NumberInSeries>1</NumberInSeries>
				<SurfacePressure>101800</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.22</Depth>
				<Temperature>289.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.22</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>2.58</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>3.08</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>3.56</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>4.08</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>4.43</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>4.77</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>4.92</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>5.04</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>5.08</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>5.02</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>4.97</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>4.87</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>4.56</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>4.34</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>4.39</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>4.47</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>4.51</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>4.48</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>4.51</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>4.31</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>3.6</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>2.56</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>24</Time>
				<Depth>1.88</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>25</Time>
				<Depth>1.51</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>26</Time>
				<Depth>0.7</Depth>
				<Temperature>289.15</Temperature>
			</Sample>
			<Sample>
				<Time>27</Time>
				<Depth>0.22</Depth>
				<Temperature>289.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
