<?xml version="1.0" encoding="utf-8"?>
<sml SdkVersion="2.6.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
	<DeviceLog>
		<Header>
			<Battery>3</Battery>
			<DateTime>2016-05-24T16:31:05</DateTime>
			<Duration>23</Duration>
			<Depth>
				<Max>1.91</Max>
				<Avg>1.51</Avg>
			</Depth>
			<Diving>
				<DiveMode>Free</DiveMode>
				<Conservatism>0</Conservatism>
				<Altitude>0</Altitude>
				<SurfaceTime>480</SurfaceTime>
				<NumberInSeries>21</NumberInSeries>
				<SurfacePressure>101000</SurfacePressure>
				<StartTissue/>
				<EndTissue/>
			</Diving>
			<SampleInterval>1</SampleInterval>
		</Header>
		<Device>
			<Name>Suunto D6i</Name>
			<SerialNumber>51670658</SerialNumber>
			<Info>
				<SW>1.2.10</SW>
				<HW>0.0.0</HW>
				<BSL>0.0.0</BSL>
			</Info>
		</Device>
		<Samples>
			<Sample>
				<Time>0</Time>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Wet Outside</Type>
						<Active>true</Active>
					</State>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>0</Time>
				<Depth>1.3</Depth>
				<Temperature>303.15</Temperature>
				<Events>
					<State>
						<Type>Dive Active</Type>
						<Active>true</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>1</Time>
				<Depth>1.3</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>2</Time>
				<Depth>1.78</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>3</Time>
				<Depth>1.71</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>4</Time>
				<Depth>1.57</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>5</Time>
				<Depth>1.63</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>6</Time>
				<Depth>1.84</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>7</Time>
				<Depth>1.77</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>8</Time>
				<Depth>1.85</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>9</Time>
				<Depth>1.91</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>10</Time>
				<Depth>1.85</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>11</Time>
				<Depth>1.83</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>12</Time>
				<Depth>1.79</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>13</Time>
				<Depth>1.71</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>14</Time>
				<Depth>1.72</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>15</Time>
				<Depth>1.71</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>16</Time>
				<Depth>1.58</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>17</Time>
				<Depth>1.52</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>18</Time>
				<Depth>1.43</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>19</Time>
				<Depth>1.2</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>20</Time>
				<Depth>1.12</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>21</Time>
				<Depth>1.13</Depth>
				<Temperature>303.15</Temperature>
			</Sample>
			<Sample>
				<Time>22</Time>
				<Depth>0.5600000000000001</Depth>
				<Temperature>303.15</Temperature>
				<Events>
					<State>
						<Type>Below Wet Activation Depth</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
			<Sample>
				<Time>23</Time>
				<Depth>0.39</Depth>
				<Temperature>303.15</Temperature>
				<Events>
					<State>
						<Type>Below Surface</Type>
						<Active>false</Active>
					</State>
				</Events>
			</Sample>
		</Samples>
	</DeviceLog>
</sml>
