# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01f0b4945cc95e24c505b053ef3025cf01cc56d971a74c8db8e23eacfbc4917ea8876876d23479d615bd2217ad8f038f4c81ab4c224e8121aaa1b66fc600dd0b

test:
  secret_key_base: 763853bcacf63247426ef1224a158f81f0b9411adbd0908e82b96bb6e26e7c06860ed87c42820eba9893863487a8a59e4d7878ea035e8938dd3ee172423da3af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
